/* Generated by wayland-scanner 1.26.0 */

/*
 * AbyssBSD Swift DE. PHASE10.md P10.3.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *abyss_menu_v1_types[] = {
	NULL,
	NULL,
	NULL,
	&wl_surface_interface,
	NULL,
};

static const struct wl_message abyss_menu_manager_v1_requests[] = {
	{ "destroy", "", abyss_menu_v1_types + 0 },
	{ "set_address", "os", abyss_menu_v1_types + 3 },
};

WL_PRIVATE const struct wl_interface abyss_menu_manager_v1_interface = {
	"abyss_menu_manager_v1", 1,
	2, abyss_menu_manager_v1_requests,
	0, NULL,
};

static const struct wl_message abyss_menubar_v1_requests[] = {
	{ "destroy", "", abyss_menu_v1_types + 0 },
};

static const struct wl_message abyss_menubar_v1_events[] = {
	{ "focused", "uss", abyss_menu_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface abyss_menubar_v1_interface = {
	"abyss_menubar_v1", 1,
	1, abyss_menubar_v1_requests,
	1, abyss_menubar_v1_events,
};

