/* Generated by wayland-scanner 1.26.0 */

/*
 * AbyssBSD Swift DE. Same terms as the rest of the tree.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface xdg_toplevel_interface;

static const struct wl_interface *abyss_window_v1_types[] = {
	&xdg_toplevel_interface,
};

static const struct wl_message abyss_window_manager_v1_requests[] = {
	{ "destroy", "", abyss_window_v1_types + 0 },
	{ "lower", "o", abyss_window_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface abyss_window_manager_v1_interface = {
	"abyss_window_manager_v1", 1,
	2, abyss_window_manager_v1_requests,
	0, NULL,
};

