// GENERATED by abyss/tools/gen-jaguar-lists.sh from themes/aqua/draw/*.dl (in name order)
// — do not edit. The compiled Jaguar draw lists, as ThemeTokens.jaguar is the
// compiled Jaguar tokens: what draws when no theme can be read, or one is
// refused. ThemeTests proves this is the file, byte for byte.

enum JaguarLists {
    static let source = ##"""
# Aqua — Jaguar's controls as draw lists (PHASE11 P11.4).
#
# Each list is the Swift recipe it replaced in de/aquadraw/Drawing.swift, op for
# op, and is proved byte-identical to it (Tests/AquaTests/DrawParityTests). Where
# the Swift did something odd, the list does it too, and says so: the gate for
# this pass is that nothing moves. Fixing what looks wrong is a change to the
# look, made later, on purpose, with the goldens updated.
#
# Coordinates are the widget's own (0 0 its top-left). See DrawList.swift for
# the format.

# The keyboard-focus halo, just outside a control. $radius is the control's.
list focusring
  rect -1.5 -1.5 w+3 h+3 $radius+1.5
  stroke fieldFocusRing 2.5
end

# Hairlines every 4 px, from 1.5 down (title bar, menu bar, toasts). $color.
list pinstripe
  rect 0 0 w h
  rules across 1.5 4 $color 1
end

# The white gel push button.
list button
  rect 0 0 w h h/2
  unless pressed fill vertical stops 0 buttonWhiteTop 1 buttonWhiteBottom
  when pressed fill vertical stops 0 shift(buttonWhiteTop, -0.08) 1 shift(buttonWhiteBottom, -0.08)
  stroke buttonWhiteBorder 1
  rect 1.5 1.5 w-3 h*0.45 h*0.45/2
  fill linear 0 1.5 0 1.5+h*0.45 stops 0 #ffffff/0.75 1 #ffffff/0.05
  text $label w/2 h/2 center color=buttonTextOnWhite
end

# The default (blue gel) push button.
list button.default
  rect 0 0 w h h/2
  unless pressed fill vertical stops 0 buttonBlueTop 0.5 buttonBlueMid 1 buttonBlueBottom
  when pressed fill vertical stops 0 shift(buttonBlueTop, -0.08) 0.5 shift(buttonBlueMid, -0.08) 1 shift(buttonBlueBottom, -0.08)
  stroke buttonBlueBorder 1
  rect 1.5 1.5 w-3 h*0.45 h*0.45/2
  fill linear 0 1.5 0 1.5+h*0.45 stops 0 #ffffff/0.75 1 #ffffff/0.05
  text $label w/2 h/2 center color=buttonTextOnBlue
end

# A text field: the label is its text, the placeholder shows when that is
# empty, and focused means it has the caret.
list textfield
  when focused rect -1.5 -1.5 w+3 h+3 4.5
  when focused stroke fieldFocusRing 2.5
  rect 0 0 w h 3
  fill fieldBackground
  innershadow fieldInsetShadow 4 5
  stroke fieldBorder 1
  push
  rect 4 0 w-8 h
  clip
  text $label 6 h/2+@fontSize*0.35 left baseline color=fieldText placeholder=fieldPlaceholder
  when focused path 6+textw(@fontSize)+1 5 6+textw(@fontSize)+1 h-5
  when focused stroke fieldCaret 1
  pop
end

# A checkbox; selected is checked.
#
# Checked, the gloss gradient fills the WHOLE box, not the 42% capsule it was
# drawn for: the Swift filled the body with fill_preserve and then added the
# capsule to the path it had kept, so the gloss filled both — `and`, below. The
# one-byte difference between "body" and "body and capsule" is why `and` exists.
# That is how it has always looked, so that is what this draws.
list checkbox
  rect 0 0 w h 3
  unless selected fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  unless selected innershadow controlInsetShadow 3 4
  unless selected stroke controlBorder 1
  when selected fill vertical stops 0 buttonBlueTop 0.5 buttonBlueMid 1 buttonBlueBottom
  when selected and rect 1 1 w-2 h*0.42 2
  when selected fill linear 0 1 0 1+h*0.42 stops 0 #ffffff/0.6 1 #ffffff/0.05
  when selected rect 0 0 w h 3
  when selected stroke buttonBlueBorder 1
  when selected path w*0.24 h*0.52 w*0.43 h*0.72 w*0.78 h*0.28
  when selected stroke controlGlyph 1.8 round
end

# A radio button: the rect is its bounding square, $r its radius.
list radio
  circle $r $r $r
  unless selected fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  when selected fill vertical stops 0 buttonBlueTop 0.5 buttonBlueMid 1 buttonBlueBottom
  unless selected stroke controlBorder 1
  when selected stroke buttonBlueBorder 1
  circle $r $r-$r*0.35 $r*0.62
  unless selected fill linear 0 0 0 $r stops 0 #ffffff/0.7 1 #ffffff/0
  when selected fill linear 0 0 0 $r stops 0 #ffffff/0.5 1 #ffffff/0
  when selected circle $r $r $r*0.34
  when selected fill controlGlyph
end

# A horizontal slider; the rect is the whole track, $thumb the thumb's centre.
list slider
  rect 0 (h-5)/2 w 5 5/2
  fill sliderTrack
  push
  clip
  rect 0 (h-5)/2 w 1.5
  fill sliderTrackEdge
  pop
  rect 0 (h-5)/2 w 5 5/2
  stroke controlBorder/0.6 1
  circle $thumb h/2 8
  fill vertical stops 0 controlWhiteTop 1 #c8c8c8
  stroke controlBorder 1
  circle $thumb h/2-8*0.3 8*0.6
  fill linear 0 h/2-8 0 h/2 stops 0 #ffffff/0.85 1 #ffffff/0
end

# A pop-up button: a white well with a blue cap on the right.
#
# The cap's gloss, like the checkbox's, fills the whole cap (fill_preserve).
list popup
  rect 0 0 w h 4
  fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  innershadow controlInsetShadow 3 4
  stroke controlBorder 1
  push
  clip
  rect w-h 0 h h
  fill vertical stops 0 buttonBlueTop 0.5 buttonBlueMid 1 buttonBlueBottom
  and rect w-h 1 h h*0.42
  fill linear 0 1 0 1+h*0.42 stops 0 #ffffff/0.5 1 #ffffff/0.02
  pop
  path w-h+0.5 1 w-h+0.5 h-1
  stroke buttonBlueBorder 1
  path w-h+h/2-3 h/2-2.5 w-h+h/2 h/2-5 w-h+h/2+3 h/2-2.5
  stroke controlGlyph 1.3 round
  path w-h+h/2-3 h/2+2.5 w-h+h/2 h/2+5 w-h+h/2+3 h/2+2.5
  stroke controlGlyph 1.3 round
  text $label (w-h)/2 h/2 center color=fieldText
  rect 0 0 w h 4
  stroke controlBorder 1
end

# A determinate progress bar. $fill is how far the blue runs (0 for none).
list progress
  rect 0 0 w h h/2
  fill progressTrack
  push
  clip
  rect 0 0 w 1.5
  fill controlInsetShadow
  pop
  push
  rect 0 0 w h h/2
  clip
  rect 0 0 $fill h
  fill vertical stops 0 buttonBlueTop 0.5 buttonBlueMid 1 buttonBlueBottom
  clip
  rect 0 0 w h
  rules slant -h 9 $fill #ffffff/0.2 3.5
  pop
  rect 0 0 w h h/2
  stroke controlBorder 1
end

# A scrollbar's channel.
#
# The inset shadow meant for the leading edge darkens the WHOLE channel by 10%:
# the Swift added the edge's rectangle to the gradient's kept path and filled
# both. Which edge it meant (left when vertical, top when not) cannot be seen
# under the wash, so this is one list for both.
list scrolltrack
  rect 0 0 w h
  fill vertical stops 0 #dedede 1 #eaeaea
  and rect 0 0 1.5 h
  fill #000000/0.1
  rect 0.5 0.5 w-1 h-1
  stroke controlBorder/0.55 1
end

# The blue gel thumb. Its gloss fills the whole thumb (fill_preserve).
list scrollthumb
  rect 0 0 w h min(w,h)/2
  fill vertical stops 0 buttonBlueTop 0.5 buttonBlueMid 1 buttonBlueBottom
  and rect 1.5 1.5 w-3 h*0.42 min(w-3,h*0.42)/2
  fill linear 0 1.5 0 1.5+h*0.42 stops 0 #ffffff/0.65 1 #ffffff/0.05
  rect 0 0 w h min(w,h)/2
  stroke buttonBlueBorder 1
end

# The scrollbar's arrow buttons; disabled when there is no travel left.
list scrollarrow.up
  rect 0 0 w h 2
  fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  innershadow controlInsetShadow 3 4
  stroke controlBorder 1
  path w/2 h/2-min(w,h)*0.26 w/2+min(w,h)*0.26 h/2+min(w,h)*0.26 w/2-min(w,h)*0.26 h/2+min(w,h)*0.26 close
  unless disabled fill buttonBlueMid
  when disabled fill controlBorder
end

list scrollarrow.down
  rect 0 0 w h 2
  fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  innershadow controlInsetShadow 3 4
  stroke controlBorder 1
  path w/2 h/2+min(w,h)*0.26 w/2+min(w,h)*0.26 h/2-min(w,h)*0.26 w/2-min(w,h)*0.26 h/2-min(w,h)*0.26 close
  unless disabled fill buttonBlueMid
  when disabled fill controlBorder
end

list scrollarrow.left
  rect 0 0 w h 2
  fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  innershadow controlInsetShadow 3 4
  stroke controlBorder 1
  path w/2-min(w,h)*0.26 h/2 w/2+min(w,h)*0.26 h/2-min(w,h)*0.26 w/2+min(w,h)*0.26 h/2+min(w,h)*0.26 close
  unless disabled fill buttonBlueMid
  when disabled fill controlBorder
end

list scrollarrow.right
  rect 0 0 w h 2
  fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  innershadow controlInsetShadow 3 4
  stroke controlBorder 1
  path w/2+min(w,h)*0.26 h/2 w/2-min(w,h)*0.26 h/2-min(w,h)*0.26 w/2-min(w,h)*0.26 h/2+min(w,h)*0.26 close
  unless disabled fill buttonBlueMid
  when disabled fill controlBorder
end

# A segmented control is drawn in passes, because a list cannot iterate over
# its segments: each segment's body, the strip's gloss, the dividers, the
# frame, then each label. Every pass's rect is the whole control; $x and $w
# are one segment's offset and width.
list segmented.segment
  rect 0 0 w h 4
  clip
  rect $x 0 $w h
  unless selected fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  when selected fill vertical stops 0 buttonBlueTop 0.5 buttonBlueMid 1 buttonBlueBottom
end

list segmented.gloss
  rect 0 0 w h 4
  clip
  rect 0 0 w h*0.45
  fill linear 0 0 0 h*0.45 stops 0 #ffffff/0.55 1 #ffffff/0.03
end

list segmented.divider
  path $x+0.5 1 $x+0.5 h-1
  stroke controlBorder/0.55 1
end

list segmented.frame
  rect 0 0 w h 4
  stroke controlBorder 1
end

list segmented.label
  unless selected text $label $x+$w/2 h/2 center color=fieldText
  when selected text $label $x+$w/2 h/2 center color=buttonTextOnBlue
end

# A tab view's content pane.
list tabpane
  rect 0 0 w h 6
  fill tabPaneBackground
  stroke tabBorder 1
end

# A tab on the pane's top edge; selected is the front one.
list tab
  rect 0 0 w h 6 top
  unless selected fill vertical stops 0 tabUnselectedTop 1 tabUnselectedBottom
  when selected fill vertical stops 0 tabSelectedTop 1 tabSelectedBottom
  stroke tabBorder 1
  text $label w/2 h/2+0.5 center color=tabText
end

# A titled group box: the title is notched into its top-left.
list groupbox
  rect 0 0 w h 5
  stroke groupBoxBorder 1
  rect 10 -6 textw(11)+8 12
  fill contentBackground
  text $label 14 4 left baseline size=11 color=controlLabel/0.75
end

# A list view's paper, its alternate-row stripe, and its frame (the scroll
# demo's list; the Finder's list view).
list listview
  rect 0 0 w h
  fill listBackground
end

list listview.stripe
  rect 0 0 w h
  fill listStripe
end

list listview.frame
  rect 0.5 0.5 w-1 h-1
  stroke controlBorder 1
end

# The selected tab merges into its pane: the pane's border under it is
# painted out. The rect is the tab; $pane is the pane's top, from the tab's.
list tab.merge
  rect 1 $pane-1 w-2 2
  fill tabPaneBackground
end

# A sheet. The window body under the title bar dims as it comes out
# ($progress 0…1); the panel hangs from the title bar with a soft shadow.
list sheet.dim
  rect 0 0 w h
  fill fade(sheetDim, $progress)
end

list sheet
  rect 0 2 w h 8 bottom
  fill sheetShadow
  rect 0 0 w h 8 bottom
  fill sheetBackground
  stroke windowBorder 1
end

# A pop-up menu: the paper, and the frame drawn over the items last. The rect
# is the whole menu surface.
list menu
  rect 0.5 0.5 w-1 h-1 5
  fill menuBackground
end

list menu.frame
  rect 0.5 0.5 w-1 h-1 5
  stroke menuBorder 1
end

# A separator: the rect is one pixel-snapped line across the menu.
list menu.separator
  rect 1 0 w-2 h
  fill menuSeparator
end

# An item's parts; the rect is the item's row across the menu, $color the
# colour its text is drawn in (on the highlight, enabled, or not).
list menu.highlight
  rect 3 0 w-6 h 3
  fill menuHighlight
end

list menu.check
  path 8 h/2+1 8+3 h/2+4 8+8 h/2-4
  stroke $color 1.6 round
end

list menu.submenu
  path w-@menu.rightInset-5 h/2-4.5 w-@menu.rightInset h/2 w-@menu.rightInset-5 h/2+4.5 close
  fill $color
end

# System Preferences' toolbar: its band, the separator along its foot, and the
# dotted divider after Show All ($x its position).
#
# The band's rectangle is stroked in the separator's colour along with the
# separator line, and so is outlined: the gradient was filled with
# fill_preserve and the line added to the kept path (HANDOFF §2.67).
list prefs.toolbar
  rect 0 0 w h
  fill vertical stops 0 prefsToolbarTop 1 prefsToolbarBottom
  and path 0 h-0.5 w h-0.5
  stroke separator 1
end

list prefs.toolbar.divider
  path $x 10 $x h-10
  stroke toolbarSeparator 1 dash=1,2
end

# A selected icon's name, on the highlight (the Finder's icon view, the
# desktop); the rect is the label's, padded.
list iconlabel.selected
  rect 0 0 w h 3
  fill menuHighlight
end

# A list view's selected row.
list listview.selection
  rect 0 0 w h
  fill menuHighlight
end

# A horizontal rule between groups; the rect is its run, one line high. (Held
# back in P11.5: Sharing's folder icon leaked its path, and this stroke
# outlined it. The icons are data since P11.8 and leak nothing.)
list rule
  path 0 0.5 w 0.5
  stroke separator 1
end
# Aqua — the window frame (PHASE11 P11.6). Laid out by `windowChrome` from
# theme.ini's [chrome] and chrome metrics; these lists are how each part looks.
# The same lists draw the toolkit's own windows and the frames undertow puts
# around foreign ones.

# The frame's shape: everything below — body, title bar, gadgets, title — is
# drawn inside it, and the border follows it.
list window.shape
  rect 0 0 w h @windowCornerRadius top
end

# The frame's body and title bar (inside window.shape).
#
# The pinstripe's first hairline is stroked together with the title bar's
# outline: the gradient was filled with fill_preserve, so the bar's rectangle
# was still the path (HANDOFF §2.67). `and` below keeps that look.
list window
  rect 0 0 w h
  fill contentBackground
  rect 0 0 w @titleBarHeight
  fill vertical stops 0 titleBarTop 1 titleBarBottom
  and path 0 1.5 w 1.5
  stroke titleBarPinstripe 1
  rect 0 0 w @titleBarHeight
  rules across 5.5 4 titleBarPinstripe 1
  path 0 0.5 w 0.5
  stroke titleBarHighlight 1
  path 0 @titleBarHeight-0.5 w @titleBarHeight-0.5
  stroke separator 1
end

# The title, centred on $x in the title bar (the layout says where); active is
# the frontmost window. `.bold` when [chrome] titleWeight = bold.
list window.title
  text $label $x h/2 center size=@chrome.titleSize role=chrome color=titleText
end

list window.title.bold
  text $label $x h/2 center bold size=@chrome.titleSize role=chrome color=titleText
end

# The border, drawn last, over everything.
list window.frame
  rect 0 0 w h @windowCornerRadius top
  stroke windowBorder 1
end

# An inactive window's frame is lighter on 10.2: one wash over the title bar.
list window.inactive
  rect 0 0 w @titleBarHeight
  fill inactiveFrameWash
end

# The traffic lights: glassy water drops. The rect is the drop's bounding
# square, $r its radius; active is the window being frontmost (the frame is
# drawn lit, and washed when it is not).
list gadget.close
  circle $r $r $r
  when active fill linear 0 0 0 h stops 0 shift(close, 0.3) 0.5 close 1 shift(close, -0.12)
  unless active fill linear 0 0 0 h stops 0 shift(trafficInactive, 0.3) 0.5 trafficInactive 1 shift(trafficInactive, -0.12)
  stroke trafficRim 0.75
  push
  circle $r $r $r-0.5
  clip
  circle $r $r-$r*0.18 $r*0.78
  fill radial $r $r-$r*0.45 0 $r $r-$r*0.35 $r*0.95 stops 0 #ffffff/0.85 0.6 #ffffff/0.25 1 #ffffff/0
  pop
  circle $r-$r*0.28 $r-$r*0.42 $r*0.16
  fill #ffffff/0.95
end

list gadget.minimize
  circle $r $r $r
  when active fill linear 0 0 0 h stops 0 shift(minimize, 0.3) 0.5 minimize 1 shift(minimize, -0.12)
  unless active fill linear 0 0 0 h stops 0 shift(trafficInactive, 0.3) 0.5 trafficInactive 1 shift(trafficInactive, -0.12)
  stroke trafficRim 0.75
  push
  circle $r $r $r-0.5
  clip
  circle $r $r-$r*0.18 $r*0.78
  fill radial $r $r-$r*0.45 0 $r $r-$r*0.35 $r*0.95 stops 0 #ffffff/0.85 0.6 #ffffff/0.25 1 #ffffff/0
  pop
  circle $r-$r*0.28 $r-$r*0.42 $r*0.16
  fill #ffffff/0.95
end

list gadget.zoom
  circle $r $r $r
  when active fill linear 0 0 0 h stops 0 shift(zoom, 0.3) 0.5 zoom 1 shift(zoom, -0.12)
  unless active fill linear 0 0 0 h stops 0 shift(trafficInactive, 0.3) 0.5 trafficInactive 1 shift(trafficInactive, -0.12)
  stroke trafficRim 0.75
  push
  circle $r $r $r-0.5
  clip
  circle $r $r-$r*0.18 $r*0.78
  fill radial $r $r-$r*0.45 0 $r $r-$r*0.35 $r*0.95 stops 0 #ffffff/0.85 0.6 #ffffff/0.25 1 #ffffff/0
  pop
  circle $r-$r*0.28 $r-$r*0.42 $r*0.16
  fill #ffffff/0.95
end

# Send to back. Jaguar has none — this is the Aqua look for a theme (or a
# person) that asks for one in [chrome]: a graphite drop bearing two
# overlapping frames, the back one hollow.
list gadget.depth
  circle $r $r $r
  fill linear 0 0 0 h stops 0 shift(trafficInactive, 0.3) 0.5 trafficInactive 1 shift(trafficInactive, -0.12)
  stroke trafficRim 0.75
  rect $r*0.45 $r*0.45 $r*0.8 $r*0.8
  stroke #3c3c3c/0.8 1
  rect $r*0.75 $r*0.75 $r*0.8 $r*0.8
  fill #ffffff/0.9
  stroke #3c3c3c/0.8 1
end

# The toolbar toggle at the title bar's right (the toolkit's own windows).
list gadget.pill
  rect 0 0 w h h/2
  stroke #000000/0.3 1
end
# Aqua — the Finder's window paint (PHASE11 P11.5): toolbar, list header,
# status bar, selection, the rename field. Its item icons are P11.8's, its
# text the toolkit's.

# The toolbar band, with the separator along its foot.
list finder.toolbar
  rect 0 0 w h
  fill vertical stops 0 toolbarTop 1 toolbarBottom
  path 0 h-0.5 w h-0.5
  stroke separator 1
end

# The Back control: a white gel capsule with a left-pointing glyph. Pressed
# while held; disabled at the top of the history.
list finder.back
  rect 0 0 w h 5
  when pressed fill vertical stops 0 controlPressedTop 1 controlPressedBottom
  unless pressed fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  unless disabled stroke controlBorder/1 1
  when disabled stroke controlBorder/0.5 1
  path w/2-4 h/2 w/2+3 h/2-5 w/2+3 h/2+5 close
  unless disabled fill toolbarGlyph
  when disabled fill toolbarGlyph/0.35
end

# The glyphs on the icon/list view switch (a segmented control, drawn first):
# four tiles on the left segment, three lines on the right. Selected is the
# list view; each glyph is white on the chosen segment.
list finder.viewswitch
  rect w/2/2-4-2/2 h/2-4-2/2 4 4
  and rect w/2/2-4-2/2+(4+2) h/2-4-2/2 4 4
  and rect w/2/2-4-2/2 h/2-4-2/2+(4+2) 4 4
  and rect w/2/2-4-2/2+(4+2) h/2-4-2/2+(4+2) 4 4
  unless selected fill controlGlyph
  when selected fill segmentGlyph
  path w/2+w/2/2-5.5 h/2-4 w/2+w/2/2-5.5+11 h/2-4
  and path w/2+w/2/2-5.5 h/2-4+4 w/2+w/2/2-5.5+11 h/2-4+4
  and path w/2+w/2/2-5.5 h/2-4+8 w/2+w/2/2-5.5+11 h/2-4+8
  when selected stroke controlGlyph 1.6
  unless selected stroke segmentGlyph 1.6
end

# The list view's column header, its foot, and a divider at column $x.
list finder.header
  rect 0 0 w h
  fill vertical stops 0 listHeaderTop 1 listHeaderBottom
  path 0 h-0.5 w h-0.5
  stroke separator 1
end

list finder.header.divider
  path $x+0.5 2 $x+0.5 h-2
  stroke separator 1
end

# The hairline along the top of the item well; the rect is one line high.
list finder.welledge
  path 0 0.5 w 0.5
  stroke separator 1
end

# A selected icon's soft blue wash; the rect is the icon.
list finder.selection
  rect -3 -3 w+6 h+6 6
  fill menuHighlight/0.22
end

# The inline rename field: a white well in the focus ring. Selected when part
# of the name is selected: $sel is that run's width. Its text is drawn next,
# then the caret, at $caret.
list finder.namefield
  rect 0 0 w h
  fill fieldBackground
  rect -1.5 -1.5 w+3 h+3 2+1.5
  stroke fieldFocusRing 2.5
  rect 0.5 0.5 w-1 h-1
  stroke fieldBorder 1
  when selected rect 4-1 2 $sel+2 h-4
  when selected fill menuHighlight
end

list finder.namefield.caret
  rect $caret 2 1 h-4
  fill fieldCaret
end

# The status bar, with the separator along its top.
list finder.status
  rect 0 0 w h
  fill vertical stops 0 statusBarTop 1 statusBarBottom
  path 0 0.5 w 0.5
  stroke separator 1
end
# Aqua — the installer's paint (PHASE11 P11.5). Its text is the toolkit's.

# The window body: Aqua's pale, the pinstripe along the top 40 px the way a
# Jaguar utility window wears it, and the separator under it.
list installer
  rect 0 0 w h
  fill contentBackground
  rect 0 0 w 40
  rules across 1.5 4 pinstripe 1
  rect 0 39.5 w 1
  fill separator
end

# A hub row: done, or (the .attention variant) still wanting an answer.
list installer.spoke
  rect 0 0 w h 6
  fill rowBackground
  stroke separator 1
end

list installer.spoke.attention
  rect 0 0 w h 6
  fill attentionBackground
  stroke separator 1
end

# A picker row, selected. Disabled is a disk that cannot be used: it is still
# shown, greyed, with its reason — never hidden.
list installer.row
  rect 0 0 w h
  unless disabled fill menuHighlight
  when disabled fill trafficInactive
end

# A control that is present but cannot be used.
list installer.veil
  rect 0 0 w h h/2
  fill disabledVeil
end
# Aqua — the desktop shell's paint: the menu bar, toasts, the Dock, the
# wallpaper (PHASE11 P11.5). Like aqua.dl, each list is the Swift it replaced,
# op for op, held to the golden gate; the text on these surfaces is still drawn
# by the toolkit's text calls until type comes by role (P11.7).

# The menu bar's background.
#
# The pinstripe's first hairline is stroked TOGETHER with the bar's outline:
# the gradient was filled with fill_preserve, so the bar's rectangle was still
# the path when the pinstripe began (HANDOFF §2.67). So the bar is outlined, 1 px,
# in the pinstripe's colour, and that is what `and` below reproduces.
list menubar
  rect 0 0 w h
  fill vertical stops 0 menuBarTop 1 menuBarBottom
  and path 0 1.5 w 1.5
  stroke menuBarBottom/0.5 1
  rect 0 0 w h
  rules across 5.5 4 menuBarBottom/0.5 1
  path 0 h-0.5 w h-0.5
  stroke menuBarBorder 1
end

# The clock: a readout, in its slot at the bar's right ($size the bar's type).
list menubar.clock
  text $label 2 h-6.5 left baseline size=$size role=readout color=menuBarText
end

# An open title's highlight; the rect is the title's slot, full height.
list menubar.highlight
  rect 0 0 w h
  fill menuHighlight
end

# The system menu's mark: an original water drop, a bulb under a point — not
# Apple's apple. Selected while its menu is open.
list menubar.system
  circle w/2 h*0.62 w*0.42
  and path w/2 h*0.08 w/2+w*0.42*0.92 h*0.62 w/2-w*0.42*0.92 h*0.62 close
  unless selected fill menuBarText
  when selected fill menuTextOnHighlight
end

# A notification toast's panel.
#
# There is no border: the Swift stroked toastBorder along a path the pinstripe
# had already stroked and so consumed — deleting that stroke moved no pixel.
# What outlines the panel is the pinstripe's first hairline, stroked with the
# kept outline (§2.67), clipped to the panel. toastBorder is a token nothing
# draws, until the look is changed on purpose.
list toast
  rect 1 2 w h @toast.corner
  fill toastShadow
  rect 0 0 w h @toast.corner
  push
  clip
  fill vertical stops 0 toastTop 1 toastBottom
  and path 0 1.5 w 1.5
  stroke toastPinstripe 1
  rect 0 0 w h
  rules across 5.5 4 toastPinstripe 1
  pop
end

# The drop that marks a toast as the system's, 13 × 13.
list toast.mark
  path w/2 0 curve w/2+w*0.55 h*0.45 w/2+w*0.5 h w/2 h curve w/2-w*0.5 h w/2-w*0.55 h*0.45 w/2 0 close
  fill systemMark
end

# The menu bar's volume item: a speaker, and one arc per third of the range —
# none when muted, which is the point of arcs rather than a fixed glyph. One
# list per level (a list cannot count); the toolkit picks by level. $color is
# the bar's text colour.
list status.volume.0
  path 0 h/2-h*0.18 w*0.32 h/2-h*0.18 w*0.32*2.1 0 w*0.32*2.1 h w*0.32 h/2+h*0.18 0 h/2+h*0.18 close
  fill $color
end

list status.volume.1
  path 0 h/2-h*0.18 w*0.32 h/2-h*0.18 w*0.32*2.1 0 w*0.32*2.1 h w*0.32 h/2+h*0.18 0 h/2+h*0.18 close
  fill $color
  arc w*0.32*2.1 h/2 w*(0.30+0.16*0) -0.9 0.9
  stroke $color 1.2
end

list status.volume.2
  path 0 h/2-h*0.18 w*0.32 h/2-h*0.18 w*0.32*2.1 0 w*0.32*2.1 h w*0.32 h/2+h*0.18 0 h/2+h*0.18 close
  fill $color
  arc w*0.32*2.1 h/2 w*(0.30+0.16*0) -0.9 0.9
  stroke $color 1.2
  arc w*0.32*2.1 h/2 w*(0.30+0.16*1) -0.9 0.9
  stroke $color 1.2
end

list status.volume.3
  path 0 h/2-h*0.18 w*0.32 h/2-h*0.18 w*0.32*2.1 0 w*0.32*2.1 h w*0.32 h/2+h*0.18 0 h/2+h*0.18 close
  fill $color
  arc w*0.32*2.1 h/2 w*(0.30+0.16*0) -0.9 0.9
  stroke $color 1.2
  arc w*0.32*2.1 h/2 w*(0.30+0.16*1) -0.9 0.9
  stroke $color 1.2
  arc w*0.32*2.1 h/2 w*(0.30+0.16*2) -0.9 0.9
  stroke $color 1.2
end

# The battery item: an outline, a terminal nub, a fill of $charge (0…1), and,
# active while charging, a bolt cut out of it. $color is the bar's text colour.
list status.battery
  rect 0.5 0.5 w-1 h-1
  stroke $color 1
  rect w h*0.3 1.5 h*0.4
  fill $color
  rect 2 2 (w-2*2)*$charge h-2*2
  fill $color
  when active path w*0.52 1 w*0.36 h*0.55 w*0.50 h*0.55 w*0.42 h-1 w*0.64 h*0.45 w*0.50 h*0.45 close
  when active fill statusGlyphCutout
end

# A desktop icon's selection: a translucent plate behind the icon. (Its label
# sits on iconlabel.selected, as a Finder icon's does — aqua.dl.)
list desktop.selection
  rect -3 -3 w+6 h+6 6
  fill menuHighlight/0.35
end

# The built-in "Aqua Blue" backdrop: a light sky top deepening to ocean blue,
# with a broad soft sheen high and left of centre. (A flat colour, gradient or
# picture chosen in desktop.ini is the person's, not the theme's, and is drawn
# by the toolkit.)
list wallpaper
  rect 0 0 w h
  fill vertical stops 0 desktopTop 0.55 desktopMiddle 1 desktopBottom
  fill radial w*0.42 h*0.30 max(w,h)*0.75 stops 0 desktopGlow 1 desktopGlow/0
end

# The Dock: its translucent shelf (the rect), the separator before the Trash
# ($x across the shelf), the running mark under a tile (its rect, 6 × 4), and
# the hovered tile's label plate.
list dock.shelf
  rect 0 0 w h h/4
  fill vertical stops 0 dockShelfTop 1 dockShelfBottom
  stroke dockShelfBorder 1
end

list dock.separator
  path $x 6 $x h-6
  stroke dockSeparator 1
end

list dock.running
  path 0 h w h w/2 0 close
  fill dockRunningMark
end

list dock.label
  rect 0 0 w h 5
  fill dockLabelBackground
end
# Aqua — the pointer (BACKLOG U.7): Jaguar's arrow, I-beam, hands, sizing
# arrows and the spinning wait disc, each a list `cursor.<name>` named as
# cursor-shape-v1 (CSS) names them, drawn in a `cursor.size` square. Every list
# works in a 24-unit grid (`scale w/24 w/24`), so the size is the theme's, and
# its header says where the hotspot is. Names not drawn here fall back
# (AquaDraw's Cursor.resolve): every edge's arrow to its axis, and so on.
# Original drawings, not Apple's artwork.

list cursor.default hotspot w*5/24 w*3/24
  push
  scale w/24 w/24
  path 5 3 5 19.5 9 16 11.6 21.8 14.4 20.6 11.8 15 16.8 15 close
  shadow #000000/0.35 0.6 1.2 1.5
  stroke #ffffff 2 round
  fill #000000
  pop
end

list cursor.context-menu hotspot w*5/24 w*3/24
  push
  scale w/24 w/24
  path 5 3 5 19.5 9 16 11.6 21.8 14.4 20.6 11.8 15 16.8 15 close
  shadow #000000/0.35 0.6 1.2 1.5
  stroke #ffffff 2 round
  fill #000000
  rect 12.5 12 9.5 10 1
  fill #ffffff
  stroke #000000 1
  path 14 15 20.5 15
  and path 14 17.5 20.5 17.5
  and path 14 20 20.5 20
  stroke #000000/0.6 1
  pop
end

list cursor.help hotspot w*5/24 w*3/24
  push
  scale w/24 w/24
  path 5 3 5 19.5 9 16 11.6 21.8 14.4 20.6 11.8 15 16.8 15 close
  shadow #000000/0.35 0.6 1.2 1.5
  stroke #ffffff 2 round
  fill #000000
  circle 17.5 17.5 5
  fill #3a78d8
  stroke #ffffff 1
  text "?" 17.5 17.5 center bold size=7.5 color=#ffffff
  pop
end

list cursor.progress hotspot w*5/24 w*3/24
  push
  scale w/24 w/24
  path 5 3 5 19.5 9 16 11.6 21.8 14.4 20.6 11.8 15 16.8 15 close
  shadow #000000/0.35 0.6 1.2 1.5
  stroke #ffffff 2 round
  fill #000000
  circle 17.5 17.5 4.8
  shadow #000000/0.3 0.5 1 1.5
  fill conic 17.5 17.5 4.8 stops 0 #e8453c 0.2 #f2b33d 0.4 #7cc444 0.6 #3a9ee4 0.8 #9a55d6 1 #e8453c
  stroke #000000/0.45 0.8
  ellipse 14.524000000000001 13.564 5.952 4.32
  fill vertical stops 0 #ffffff/0.7 1 #ffffff/0.05
  pop
end

list cursor.wait hotspot w/2 w/2
  push
  scale w/24 w/24
  circle 12 12 9
  shadow #000000/0.3 0.5 1 1.5
  fill conic 12 12 9 stops 0 #e8453c 0.2 #f2b33d 0.4 #7cc444 0.6 #3a9ee4 0.8 #9a55d6 1 #e8453c
  stroke #000000/0.45 1
  ellipse 6.42 4.62 11.16 8.1
  fill vertical stops 0 #ffffff/0.7 1 #ffffff/0.05
  pop
end

list cursor.pointer hotspot w*9.8/24 w*2.5/24
  push
  scale w/24 w/24
  rect 6.5 13 14.5 8.5 3.5
  shadow #000000/0.35 0.6 1.2 1.5
  rect 3.2 12.2 6.5 3.2 3.25
  fill #ffffff
  stroke #000000 1
  rect 8 2 3.6 13 1.8
  fill #ffffff
  stroke #000000 1
  rect 11.6 8 3.4 8 1.7
  fill #ffffff
  stroke #000000 1
  rect 15 9 3.2 7.5 1.6
  fill #ffffff
  stroke #000000 1
  rect 18.2 10.5 2.8 6.5 1.4
  fill #ffffff
  stroke #000000 1
  rect 6.5 13 14.5 8.5 3.5
  fill #ffffff
  stroke #000000 1
  pop
end

list cursor.grab hotspot w/2 w/2
  push
  scale w/24 w/24
  rect 6 12 13.5 9.5 4
  shadow #000000/0.35 0.6 1.2 1.5
  rect 2.2 11.5 6.5 3.2 3.25
  fill #ffffff
  stroke #000000 1
  rect 6.2 5 3.3 10 1.65
  fill #ffffff
  stroke #000000 1
  rect 9.6 3 3.3 12 1.65
  fill #ffffff
  stroke #000000 1
  rect 13 3.5 3.3 11.5 1.65
  fill #ffffff
  stroke #000000 1
  rect 16.4 5.5 3.1 9.5 1.55
  fill #ffffff
  stroke #000000 1
  rect 6 12 13.5 9.5 4
  fill #ffffff
  stroke #000000 1
  pop
end

list cursor.grabbing hotspot w/2 w/2
  push
  scale w/24 w/24
  rect 6.5 10.5 13.5 9.5 4
  shadow #000000/0.35 0.6 1.2 1.5
  rect 4.5 12 5 3.2 2.5
  fill #ffffff
  stroke #000000 1
  rect 7 8.5 3.4 5 1.7
  fill #ffffff
  stroke #000000 1
  rect 10.4 8 3.4 5 1.7
  fill #ffffff
  stroke #000000 1
  rect 13.8 8 3.4 5 1.7
  fill #ffffff
  stroke #000000 1
  rect 17.2 8.5 3.2 5 1.6
  fill #ffffff
  stroke #000000 1
  rect 6.5 10.5 13.5 9.5 4
  fill #ffffff
  stroke #000000 1
  pop
end

list cursor.text hotspot w/2 w/2
  push
  scale w/24 w/24
  path 9 3.5 11 3.5 12 4.5 13 3.5 15 3.5
  and path 12 4.5 12 19.5
  and path 9 20.5 11 20.5 12 19.5 13 20.5 15 20.5
  and path 10 12 14 12
  stroke #ffffff 3 round
  stroke #000000 1.2
  pop
end

list cursor.crosshair hotspot w/2 w/2
  push
  scale w/24 w/24
  path 12 3 12 21
  and path 3 12 21 12
  stroke #ffffff 3 round
  stroke #000000 1.2
  pop
end

list cursor.alias hotspot w*5/24 w*3/24
  push
  scale w/24 w/24
  path 5 3 5 19.5 9 16 11.6 21.8 14.4 20.6 11.8 15 16.8 15 close
  shadow #000000/0.35 0.6 1.2 1.5
  stroke #ffffff 2 round
  fill #000000
  rect 12.5 13 9 8.5 1.5
  fill #ffffff
  stroke #000000 1
  path 15 19.5 curve 15 16.5 16.5 15.5 18.5 15.5
  stroke #000000 1.2
  path 18 13.5 20.5 15.5 18 17.5 close
  fill #000000
  pop
end

list cursor.copy hotspot w*5/24 w*3/24
  push
  scale w/24 w/24
  path 5 3 5 19.5 9 16 11.6 21.8 14.4 20.6 11.8 15 16.8 15 close
  shadow #000000/0.35 0.6 1.2 1.5
  stroke #ffffff 2 round
  fill #000000
  circle 17 17 5
  fill #3fae3f
  stroke #ffffff 1
  path 17 14.2 17 19.8
  and path 14.2 17 19.8 17
  stroke #ffffff 1.6
  pop
end

list cursor.move hotspot w/2 w/2
  push
  scale w/24 w/24
  path 3 12 7 8 7 10.8 17 10.8 17 8 21 12 17 16 17 13.2 7 13.2 7 16 close
  and path 12 3 16 7 13.2 7 13.2 17 16 17 12 21 8 17 10.8 17 10.8 7 8 7 close
  shadow #000000/0.35 0.6 1.2 1.5
  stroke #ffffff 2 round
  fill #000000
  pop
end

list cursor.not-allowed hotspot w/2 w/2
  push
  scale w/24 w/24
  circle 12 12 7.5
  stroke #ffffff 4.5
  stroke #d8261c 2.5
  path 6.9 6.9 17.1 17.1
  stroke #ffffff 4.5
  stroke #d8261c 2.5
  pop
end

list cursor.ew-resize hotspot w/2 w/2
  push
  scale w/24 w/24
  path 3 12 7 8 7 10.8 17 10.8 17 8 21 12 17 16 17 13.2 7 13.2 7 16 close
  shadow #000000/0.35 0.6 1.2 1.5
  stroke #ffffff 2 round
  fill #000000
  pop
end

list cursor.ns-resize hotspot w/2 w/2
  push
  scale w/24 w/24
  path 12 3 16 7 13.2 7 13.2 17 16 17 12 21 8 17 10.8 17 10.8 7 8 7 close
  shadow #000000/0.35 0.6 1.2 1.5
  stroke #ffffff 2 round
  fill #000000
  pop
end

list cursor.nwse-resize hotspot w/2 w/2
  push
  scale w/24 w/24
  push
  move 12 12
  rotate pi/4
  move -12 -12
  path 3 12 7 8 7 10.8 17 10.8 17 8 21 12 17 16 17 13.2 7 13.2 7 16 close
  shadow #000000/0.35 0.6 1.2 1.5
  stroke #ffffff 2 round
  fill #000000
  pop
  pop
end

list cursor.nesw-resize hotspot w/2 w/2
  push
  scale w/24 w/24
  push
  move 12 12
  rotate -pi/4
  move -12 -12
  path 3 12 7 8 7 10.8 17 10.8 17 8 21 12 17 16 17 13.2 7 13.2 7 16 close
  shadow #000000/0.35 0.6 1.2 1.5
  stroke #ffffff 2 round
  fill #000000
  pop
  pop
end
# Aqua — the Dock's tiles (PHASE11 P11.8): a rounded tile in the app's hue
# with a top sheen and a white emblem, and the Trash, empty and full. The rect
# is the tile's square. Original glyphs, not Apple's artwork.


list dock.icon.finder
  rect 0 0 w h w*0.22
  fill vertical stops 0 #5a86c4 1 #2f5698
  rect 2 2 w-4 h*0.42 w*0.22*0.7
  fill #ffffff/0.22
  rect w*0.24 w*0.34+w*0.06 w*0.52 w*0.34 w*0.04
  fill #ffffff/0.95
  rect w*0.24 w*0.34 w*0.52*0.42 w*0.10 w*0.03
  fill #ffffff/0.95
end

list dock.icon.browser
  rect 0 0 w h w*0.22
  fill vertical stops 0 #3fb0a6 1 #1d7d78
  rect 2 2 w-4 h*0.42 w*0.22*0.7
  fill #ffffff/0.22
  circle w/2 w/2 w*0.26
  stroke #ffffff/0.95 w*0.05
  circle w/2 w/2 w*0.26*0.5
  and ellipse w/2-w*0.26*0.45 w/2-w*0.26 w*0.26*0.45*2 w*0.26*2
  and path w/2-w*0.26 w/2 w/2+w*0.26 w/2
  stroke #ffffff/0.95 w*0.05
end

list dock.icon.mail
  rect 0 0 w h w*0.22
  fill vertical stops 0 #6fa8e6 1 #3a6fc0
  rect 2 2 w-4 h*0.42 w*0.22*0.7
  fill #ffffff/0.22
  rect w*0.24 w*0.34 w*0.52 w*0.32 w*0.03
  fill #ffffff/0.95
  path w*0.24+w*0.02 w*0.34+w*0.02 w*0.24+w*0.52/2 w*0.34+w*0.32*0.55 w*0.24+w*0.52-w*0.02 w*0.34+w*0.02
  stroke rgba(0.3, 0.45, 0.7, 0.9) w*0.045
end

list dock.icon.music
  rect 0 0 w h w*0.22
  fill vertical stops 0 #c06fd0 1 #8236a8
  rect 2 2 w-4 h*0.42 w*0.22*0.7
  fill #ffffff/0.22
  path w*0.42 w*0.30 w*0.42 w*0.64
  stroke #ffffff/0.95 w*0.06
  path w*0.62 w*0.26 w*0.62 w*0.60
  stroke #ffffff/0.95 w*0.06
  path w*0.42 w*0.30 w*0.62 w*0.26
  stroke #ffffff/0.95 w*0.06
  circle w*0.36 w*0.64 w*0.07
  fill #ffffff/0.95
  circle w*0.56 w*0.60 w*0.07
  fill #ffffff/0.95
end

list dock.icon.prefs
  rect 0 0 w h w*0.22
  fill vertical stops 0 #9aa2ad 1 #5c636e
  rect 2 2 w-4 h*0.42 w*0.22*0.7
  fill #ffffff/0.22
  push
  move w/2 w/2
  rotate 0*pi/4
  rect -w*0.04 -w*0.2-w*0.09 w*0.08 w*0.1
  fill #ffffff/0.95
  pop
  push
  move w/2 w/2
  rotate 1*pi/4
  rect -w*0.04 -w*0.2-w*0.09 w*0.08 w*0.1
  fill #ffffff/0.95
  pop
  push
  move w/2 w/2
  rotate 2*pi/4
  rect -w*0.04 -w*0.2-w*0.09 w*0.08 w*0.1
  fill #ffffff/0.95
  pop
  push
  move w/2 w/2
  rotate 3*pi/4
  rect -w*0.04 -w*0.2-w*0.09 w*0.08 w*0.1
  fill #ffffff/0.95
  pop
  push
  move w/2 w/2
  rotate 4*pi/4
  rect -w*0.04 -w*0.2-w*0.09 w*0.08 w*0.1
  fill #ffffff/0.95
  pop
  push
  move w/2 w/2
  rotate 5*pi/4
  rect -w*0.04 -w*0.2-w*0.09 w*0.08 w*0.1
  fill #ffffff/0.95
  pop
  push
  move w/2 w/2
  rotate 6*pi/4
  rect -w*0.04 -w*0.2-w*0.09 w*0.08 w*0.1
  fill #ffffff/0.95
  pop
  push
  move w/2 w/2
  rotate 7*pi/4
  rect -w*0.04 -w*0.2-w*0.09 w*0.08 w*0.1
  fill #ffffff/0.95
  pop
  circle w/2 w/2 w*0.2
  fill #ffffff/0.95
  circle w/2 w/2 w*0.2*0.45
  fill rgba(0.36, 0.4, 0.45, 1)
end

list dock.icon.genericApp
  rect 0 0 w h w*0.22
  fill vertical stops 0 #b8beca 1 #7c8494
  rect 2 2 w-4 h*0.42 w*0.22*0.7
  fill #ffffff/0.22
  rect w*0.26 w*0.30 w*0.48 w*0.4 w*0.03
  fill #ffffff/0.95
  rect w*0.26 w*0.30 w*0.48 w*0.1
  fill rgba(0.4, 0.45, 0.55, 0.9)
end

list dock.icon.terminal
  rect 0 0 w h w*0.22
  fill vertical stops 0 #4b5058 1 #1d2025
  rect w*0.13 w*0.15 w*0.74 w*0.6 w*0.05
  fill vertical stops 0 #0d1f15 1 #06110b
  rect 2 2 w-4 h*0.42 w*0.22*0.7
  fill #ffffff/0.18
  path w*0.24 w*0.3 w*0.38 w*0.42 w*0.24 w*0.54
  stroke #7dff9a w*0.055 round
  path w*0.44 w*0.57 w*0.62 w*0.57
  stroke #7dff9a w*0.055 round
  rect w*0.36 w*0.8 w*0.28 w*0.055 w*0.02
  fill #ffffff/0.45
end

list dock.icon.agent
  # The Agent (PHASE18 P18.8b): a speech bubble on Aqua blue — someone to
  # ask — and a small padlock, because it is asked from inside a jail.
  rect 0 0 w h w*0.22
  fill vertical stops 0 #79b2ff 1 #1d5bcc
  rect 2 2 w-4 h*0.42 w*0.22*0.7
  fill #ffffff/0.22
  rect w*0.14 w*0.18 w*0.72 w*0.46 w*0.13
  fill #ffffff
  path w*0.28 w*0.6 w*0.22 w*0.8 w*0.44 w*0.62 close
  fill #ffffff
  circle w*0.33 w*0.41 w*0.055
  fill #1d5bcc
  circle w*0.5 w*0.41 w*0.055
  fill #1d5bcc
  circle w*0.67 w*0.41 w*0.055
  fill #1d5bcc
  path w*0.665 w*0.7 w*0.665 w*0.63 w*0.815 w*0.63 w*0.815 w*0.7
  stroke #e8b23a w*0.045 round
  rect w*0.6 w*0.69 w*0.28 w*0.19 w*0.035
  fill vertical stops 0 #ffd76a 1 #d99a1e
  circle w*0.74 w*0.78 w*0.025
  fill #6b4a0c
end

list dock.icon.trash
  path w*0.30 w*0.34 w*0.70 w*0.34 w*0.64 w*0.74 w*0.36 w*0.74 close
  stroke rgba(0.78, 0.80, 0.85, 1) w*0.05
  path w*0.44 w*0.36 w*0.44 w*0.72
  stroke rgba(0.78, 0.80, 0.85, 1) w*0.05
  path w*0.5 w*0.36 w*0.5 w*0.72
  stroke rgba(0.78, 0.80, 0.85, 1) w*0.05
  path w*0.56 w*0.36 w*0.56 w*0.72
  stroke rgba(0.78, 0.80, 0.85, 1) w*0.05
  path w*0.26 w*0.30 w*0.74 w*0.30
  stroke rgba(0.78, 0.80, 0.85, 1) w*0.05
  path w*0.42 w*0.30 w*0.44 w*0.24 w*0.56 w*0.24 w*0.58 w*0.30
  stroke rgba(0.78, 0.80, 0.85, 1) w*0.05
end

list dock.icon.trashFull
  # crumpled paper heaped above the rim, under the wire mesh
  circle w*0.4 w*0.3 w*0.09
  fill rgba(0.94, 0.93, 0.88, 1)
  circle w*0.56 w*0.28 w*0.1
  fill rgba(0.94, 0.93, 0.88, 1)
  circle w*0.48 w*0.22 w*0.07
  fill rgba(0.94, 0.93, 0.88, 1)
  path w*0.40 w*0.30 w*0.50 w*0.26
  and path w*0.52 w*0.32 w*0.60 w*0.27
  stroke rgba(0.72, 0.71, 0.66, 1) w*0.025
  path w*0.30 w*0.34 w*0.70 w*0.34 w*0.64 w*0.74 w*0.36 w*0.74 close
  stroke rgba(0.78, 0.80, 0.85, 1) w*0.05
  path w*0.44 w*0.36 w*0.44 w*0.72
  stroke rgba(0.78, 0.80, 0.85, 1) w*0.05
  path w*0.5 w*0.36 w*0.5 w*0.72
  stroke rgba(0.78, 0.80, 0.85, 1) w*0.05
  path w*0.56 w*0.36 w*0.56 w*0.72
  stroke rgba(0.78, 0.80, 0.85, 1) w*0.05
  path w*0.26 w*0.30 w*0.74 w*0.30
  stroke rgba(0.78, 0.80, 0.85, 1) w*0.05
  path w*0.42 w*0.30 w*0.44 w*0.24 w*0.56 w*0.24 w*0.58 w*0.30
  stroke rgba(0.78, 0.80, 0.85, 1) w*0.05
end
# Aqua — the Finder's item icons (PHASE11 P11.8): folder, document,
# application, volume. The rect is the icon's square. A bundle's own artwork
# (AppIcon) is drawn instead when it has some; these are the kinds' own.
#
# A `.small` variant is drawn below @icon.smallBelow points (24): the
# document's ruled lines are only legible at full size.


list icon.folder
  rect w*0.04 h*0.10 w*0.92*0.44 h*0.22 w*0.05
  fill #6f9cd4
  rect w*0.04 h*0.22 w*0.92 h*0.66 w*0.07
  fill vertical stops 0 rgb(0.62, 0.78, 0.94) 0.5 rgb(0.44, 0.63, 0.86) 1 rgb(0.31, 0.50, 0.76)
  rect w*0.04+w*0.05 h*0.22+h*0.04 w*0.92-w*0.10 h*0.66*0.34 w*0.05
  fill rgba(1, 1, 1, 0.28)
  rect w*0.04 h*0.22 w*0.92 h*0.66 w*0.07
  stroke rgba(0.16, 0.28, 0.45, 0.55) max(0.6, w*0.02)
end

list icon.document
  path w*0.16 h*0.06 w*0.16+w*0.68-w*0.68*0.32 h*0.06 w*0.16+w*0.68 h*0.06+w*0.68*0.32 w*0.16+w*0.68 h*0.06+h*0.88 w*0.16 h*0.06+h*0.88 close
  fill vertical stops 0 #ffffff 1 rgb(0.90, 0.91, 0.93)
  stroke rgba(0.45, 0.47, 0.52, 0.9) max(0.6, w*0.02)
  path w*0.16+w*0.68-w*0.68*0.32 h*0.06 w*0.16+w*0.68 h*0.06+w*0.68*0.32 w*0.16+w*0.68-w*0.68*0.32 h*0.06+w*0.68*0.32 close
  fill rgba(0.78, 0.80, 0.85, 1)
  stroke rgba(0.45, 0.47, 0.52, 0.9) max(0.6, w*0.02)
  path w*0.16+w*0.68*0.14 h*0.06+h*0.88*(0.46+0*0.12) w*0.16+w*0.68*0.86 h*0.06+h*0.88*(0.46+0*0.12)
  and path w*0.16+w*0.68*0.14 h*0.06+h*0.88*(0.46+1*0.12) w*0.16+w*0.68*0.86 h*0.06+h*0.88*(0.46+1*0.12)
  and path w*0.16+w*0.68*0.14 h*0.06+h*0.88*(0.46+2*0.12) w*0.16+w*0.68*0.86 h*0.06+h*0.88*(0.46+2*0.12)
  and path w*0.16+w*0.68*0.14 h*0.06+h*0.88*(0.46+3*0.12) w*0.16+w*0.68*0.86 h*0.06+h*0.88*(0.46+3*0.12)
  stroke rgba(0.55, 0.58, 0.64, 0.8) max(0.6, w*0.018)
end

list icon.document.small
  path w*0.16 h*0.06 w*0.16+w*0.68-w*0.68*0.32 h*0.06 w*0.16+w*0.68 h*0.06+w*0.68*0.32 w*0.16+w*0.68 h*0.06+h*0.88 w*0.16 h*0.06+h*0.88 close
  fill vertical stops 0 #ffffff 1 rgb(0.90, 0.91, 0.93)
  stroke rgba(0.45, 0.47, 0.52, 0.9) max(0.6, w*0.02)
  path w*0.16+w*0.68-w*0.68*0.32 h*0.06 w*0.16+w*0.68 h*0.06+w*0.68*0.32 w*0.16+w*0.68-w*0.68*0.32 h*0.06+w*0.68*0.32 close
  fill rgba(0.78, 0.80, 0.85, 1)
  stroke rgba(0.45, 0.47, 0.52, 0.9) max(0.6, w*0.02)
end

list icon.application
  rect w*0.08 h*0.08 w*0.84 h*0.84 w*0.84*0.22
  fill vertical stops 0 rgb(0.55, 0.72, 0.95) 1 rgb(0.18, 0.38, 0.74)
  rect w*0.08+w*0.84*0.06 h*0.08+h*0.84*0.06 w*0.84*0.88 h*0.84*0.40 w*0.84*0.16
  fill rgba(1, 1, 1, 0.30)
  text "A" w*0.08+w*0.84/2 h*0.08+h*0.84/2 center bold size=max(7, h*0.84*0.55) color=rgba(1, 1, 1, 0.95)
  rect w*0.08 h*0.08 w*0.84 h*0.84 w*0.84*0.22
  stroke rgba(0.10, 0.22, 0.45, 0.6) max(0.6, w*0.02)
end

list icon.disk
  rect w*0.06 h*0.22 w*0.88 h*0.58 w*0.08
  fill vertical stops 0 rgb(0.90, 0.91, 0.94) 1 rgb(0.63, 0.65, 0.70)
  rect w*0.06+w*0.04 h*0.22+h*0.04 w*0.88-w*0.08 h*0.58*0.34 w*0.05
  fill rgba(1, 1, 1, 0.45)
  rect w*0.06 h*0.22 w*0.88 h*0.58 w*0.08
  stroke rgba(0.35, 0.37, 0.42, 0.85) max(0.6, w*0.02)
  rect w*0.06+w*0.88*0.14 h*0.22+h*0.58*0.70 w*0.88*0.44 max(1, h*0.045)
  fill rgba(0.45, 0.47, 0.52, 0.75)
  circle w*0.06+w*0.88*0.80 h*0.22+h*0.58*0.74 max(1, w*0.045)
  fill rgba(0.35, 0.62, 0.92, 1)
end
# Aqua — System Preferences' pane icons (PHASE11 P11.8). Original, stylized
# glyphs in the Jaguar idiom (glossy tiles, water circles, simple white
# emblems) — not Apple's artwork. Each is self-contained, so a theme replaces
# one icon without the rest. The rect is the icon's square.
#
# Each list is the Swift painter it replaced, op for op, proved byte-identical
# (IconParityTests). Where the Swift filled a kept path (HANDOFF §2.67), the
# list does too, with `and`, and says so.

list icon.showAll
  rect w*0.18+0*(w-2*(w*0.18))*0.36 h*0.18+0*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #9aa0a6
  rect w*0.18+1*(w-2*(w*0.18))*0.36 h*0.18+0*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #9aa0a6
  rect w*0.18+2*(w-2*(w*0.18))*0.36 h*0.18+0*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #9aa0a6
  rect w*0.18+0*(w-2*(w*0.18))*0.36 h*0.18+1*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #9aa0a6
  rect w*0.18+1*(w-2*(w*0.18))*0.36 h*0.18+1*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #9aa0a6
  rect w*0.18+2*(w-2*(w*0.18))*0.36 h*0.18+1*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #9aa0a6
  rect w*0.18+0*(w-2*(w*0.18))*0.36 h*0.18+2*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #9aa0a6
  rect w*0.18+1*(w-2*(w*0.18))*0.36 h*0.18+2*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #9aa0a6
  rect w*0.18+2*(w-2*(w*0.18))*0.36 h*0.18+2*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #9aa0a6
end

list icon.dock
  rect w*0.18+0*(w-2*(w*0.18))*0.36 h*0.18+0*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #4e8df0
  rect w*0.18+1*(w-2*(w*0.18))*0.36 h*0.18+0*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #4e8df0
  rect w*0.18+2*(w-2*(w*0.18))*0.36 h*0.18+0*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #4e8df0
  rect w*0.18+0*(w-2*(w*0.18))*0.36 h*0.18+1*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #4e8df0
  rect w*0.18+1*(w-2*(w*0.18))*0.36 h*0.18+1*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #4e8df0
  rect w*0.18+2*(w-2*(w*0.18))*0.36 h*0.18+1*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #4e8df0
  rect w*0.18+0*(w-2*(w*0.18))*0.36 h*0.18+2*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #4e8df0
  rect w*0.18+1*(w-2*(w*0.18))*0.36 h*0.18+2*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #4e8df0
  rect w*0.18+2*(w-2*(w*0.18))*0.36 h*0.18+2*(h-2*(h*0.18))*0.36 (w-2*(w*0.18))*0.26 (h-2*(h*0.18))*0.26 1.5
  fill #4e8df0
end

list icon.displays
  rect w*0.1 h*0.1 (w-2*(w*0.1)) (h-2*(h*0.1))*0.72 3
  fill vertical stops 0 #bfd6f5 1 #3f74c9
  rect w*0.1 h*0.1 (w-2*(w*0.1)) (h-2*(h*0.1))*0.72 3
  stroke rgba(0.9, 0.9, 0.95, 0.9) 1.5
  rect w*0.1+(w-2*(w*0.1))/2-(w-2*(w*0.1))*0.06 h*0.1+(h-2*(h*0.1))*0.72 (w-2*(w*0.1))*0.12 (h-2*(h*0.1))*0.16
  fill #c7ccd2
  rect w*0.1+(w-2*(w*0.1))/2-(w-2*(w*0.1))*0.22 h*0.1+(h-2*(h*0.1))*0.9 (w-2*(w*0.1))*0.44 (h-2*(h*0.1))*0.1
  fill #c7ccd2
end

list icon.desktop
  rect w*0.1 h*0.1 (w-2*(w*0.1)) (h-2*(h*0.1))*0.72 3
  fill vertical stops 0 #bfd6f5 1 #3f74c9
  # the sun is added to the screen's kept path, so the whole screen fills yellow (§2.67)
  and path w*0.1+(w-2*(w*0.1))-3 h*0.1 arc w*0.1+(w-2*(w*0.1))*0.3 h*0.1+(h-2*(h*0.1))*0.72*0.35 (w-2*(w*0.1))*0.1 0 2*pi
  fill #ffd34d
  path w*0.1 h*0.1+(h-2*(h*0.1))*0.72 w*0.1+(w-2*(w*0.1))*0.5 h*0.1+(h-2*(h*0.1))*0.72*0.5 w*0.1+(w-2*(w*0.1)) h*0.1+(h-2*(h*0.1))*0.72 close
  fill #2e7d32
  rect w*0.1 h*0.1 (w-2*(w*0.1)) (h-2*(h*0.1))*0.72 3
  stroke rgba(0.9, 0.9, 0.95, 0.9) 1.5
  rect w*0.1+(w-2*(w*0.1))/2-(w-2*(w*0.1))*0.06 h*0.1+(h-2*(h*0.1))*0.72 (w-2*(w*0.1))*0.12 (h-2*(h*0.1))*0.16
  fill #c7ccd2
  rect w*0.1+(w-2*(w*0.1))/2-(w-2*(w*0.1))*0.22 h*0.1+(h-2*(h*0.1))*0.9 (w-2*(w*0.1))*0.44 (h-2*(h*0.1))*0.1
  fill #c7ccd2
end

list icon.sound
  path w*0.14 h*0.14+(h-2*(h*0.14))*0.35 w*0.14+(w-2*(w*0.14))*0.32 h*0.14+(h-2*(h*0.14))*0.35 w*0.14+(w-2*(w*0.14))*0.6 h*0.14+(h-2*(h*0.14))*0.1 w*0.14+(w-2*(w*0.14))*0.6 h*0.14+(h-2*(h*0.14))*0.9 w*0.14+(w-2*(w*0.14))*0.32 h*0.14+(h-2*(h*0.14))*0.65 w*0.14 h*0.14+(h-2*(h*0.14))*0.65 close
  fill #8c9298
  arc w*0.14+(w-2*(w*0.14))*0.62 h*0.14+(h-2*(h*0.14))/2 (w-2*(w*0.14))*(0.12*1+0.16) -0.6 0.6
  stroke rgba(0.27, 0.55, 0.9, 0.9) 2
  arc w*0.14+(w-2*(w*0.14))*0.62 h*0.14+(h-2*(h*0.14))/2 (w-2*(w*0.14))*(0.12*2+0.16) -0.6 0.6
  stroke rgba(0.27, 0.55, 0.9, 0.9) 2
end

list icon.network
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2
  fill linear 0 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2 0 h*0.08+(h-2*(h*0.08))/2+(w-2*(w*0.08))/2 stops 0 shift(#2f6fd0, 0.3) 1 shift(#2f6fd0, -0.12)
  stroke #000000/0.25 1
  push
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2-0.5
  clip
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.2 (w-2*(w*0.08))/2*0.8
  fill radial w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.5 0 w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.4 (w-2*(w*0.08))/2 stops 0 #ffffff/0.6 1 #ffffff/0
  pop
  push
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2-1
  clip
  arc w*0.08+(w-2*(w*0.08))/2+-1*(w-2*(w*0.08))/2*0.6 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2 -pi/2 pi/2
  stroke #ffffff/0.6 1
  arc w*0.08+(w-2*(w*0.08))/2+0*(w-2*(w*0.08))/2*0.6 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2 -pi/2 pi/2
  stroke #ffffff/0.6 1
  arc w*0.08+(w-2*(w*0.08))/2+1*(w-2*(w*0.08))/2*0.6 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2 -pi/2 pi/2
  stroke #ffffff/0.6 1
  path w*0.08+(w-2*(w*0.08))/2-(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+-1*(w-2*(w*0.08))/2*0.5 w*0.08+(w-2*(w*0.08))/2+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+-1*(w-2*(w*0.08))/2*0.5
  stroke #ffffff/0.6 1
  path w*0.08+(w-2*(w*0.08))/2-(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+0*(w-2*(w*0.08))/2*0.5 w*0.08+(w-2*(w*0.08))/2+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+0*(w-2*(w*0.08))/2*0.5
  stroke #ffffff/0.6 1
  path w*0.08+(w-2*(w*0.08))/2-(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+1*(w-2*(w*0.08))/2*0.5 w*0.08+(w-2*(w*0.08))/2+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+1*(w-2*(w*0.08))/2*0.5
  stroke #ffffff/0.6 1
  pop
end

list icon.international
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2
  fill linear 0 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2 0 h*0.08+(h-2*(h*0.08))/2+(w-2*(w*0.08))/2 stops 0 shift(#2f6fd0, 0.3) 1 shift(#2f6fd0, -0.12)
  stroke #000000/0.25 1
  push
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2-0.5
  clip
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.2 (w-2*(w*0.08))/2*0.8
  fill radial w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.5 0 w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.4 (w-2*(w*0.08))/2 stops 0 #ffffff/0.6 1 #ffffff/0
  pop
  push
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2-1
  clip
  arc w*0.08+(w-2*(w*0.08))/2+-1*(w-2*(w*0.08))/2*0.6 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2 -pi/2 pi/2
  stroke #ffffff/0.6 1
  arc w*0.08+(w-2*(w*0.08))/2+0*(w-2*(w*0.08))/2*0.6 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2 -pi/2 pi/2
  stroke #ffffff/0.6 1
  arc w*0.08+(w-2*(w*0.08))/2+1*(w-2*(w*0.08))/2*0.6 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2 -pi/2 pi/2
  stroke #ffffff/0.6 1
  path w*0.08+(w-2*(w*0.08))/2-(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+-1*(w-2*(w*0.08))/2*0.5 w*0.08+(w-2*(w*0.08))/2+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+-1*(w-2*(w*0.08))/2*0.5
  stroke #ffffff/0.6 1
  path w*0.08+(w-2*(w*0.08))/2-(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+0*(w-2*(w*0.08))/2*0.5 w*0.08+(w-2*(w*0.08))/2+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+0*(w-2*(w*0.08))/2*0.5
  stroke #ffffff/0.6 1
  path w*0.08+(w-2*(w*0.08))/2-(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+1*(w-2*(w*0.08))/2*0.5 w*0.08+(w-2*(w*0.08))/2+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+1*(w-2*(w*0.08))/2*0.5
  stroke #ffffff/0.6 1
  pop
end

list icon.internetIcon
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2
  fill linear 0 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2 0 h*0.08+(h-2*(h*0.08))/2+(w-2*(w*0.08))/2 stops 0 shift(#2f6fd0, 0.3) 1 shift(#2f6fd0, -0.12)
  stroke #000000/0.25 1
  push
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2-0.5
  clip
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.2 (w-2*(w*0.08))/2*0.8
  fill radial w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.5 0 w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.4 (w-2*(w*0.08))/2 stops 0 #ffffff/0.6 1 #ffffff/0
  pop
  push
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2-1
  clip
  arc w*0.08+(w-2*(w*0.08))/2+-1*(w-2*(w*0.08))/2*0.6 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2 -pi/2 pi/2
  stroke #ffffff/0.6 1
  arc w*0.08+(w-2*(w*0.08))/2+0*(w-2*(w*0.08))/2*0.6 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2 -pi/2 pi/2
  stroke #ffffff/0.6 1
  arc w*0.08+(w-2*(w*0.08))/2+1*(w-2*(w*0.08))/2*0.6 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2 -pi/2 pi/2
  stroke #ffffff/0.6 1
  path w*0.08+(w-2*(w*0.08))/2-(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+-1*(w-2*(w*0.08))/2*0.5 w*0.08+(w-2*(w*0.08))/2+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+-1*(w-2*(w*0.08))/2*0.5
  stroke #ffffff/0.6 1
  path w*0.08+(w-2*(w*0.08))/2-(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+0*(w-2*(w*0.08))/2*0.5 w*0.08+(w-2*(w*0.08))/2+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+0*(w-2*(w*0.08))/2*0.5
  stroke #ffffff/0.6 1
  path w*0.08+(w-2*(w*0.08))/2-(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+1*(w-2*(w*0.08))/2*0.5 w*0.08+(w-2*(w*0.08))/2+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2+1*(w-2*(w*0.08))/2*0.5
  stroke #ffffff/0.6 1
  pop
end

list icon.startupDisk
  rect w*0.08 h*0.08 (w-2*(w*0.08)) (h-2*(h*0.08)) (w-2*(w*0.08))*0.22
  fill vertical stops 0 #eaecee 1 #b9bdc2
  # the gloss fills the whole tile: its capsule joins the kept path (HANDOFF §2.67)
  and rect w*0.08+1 h*0.08+1 (w-2*(w*0.08))-2 (h-2*(h*0.08))*0.42 ((w-2*(w*0.08))-2)*0.22
  fill linear 0 h*0.08+1 0 h*0.08+1+(h-2*(h*0.08))*0.42 stops 0 #ffffff/0.7 1 #ffffff/0.05
  rect w*0.08 h*0.08 (w-2*(w*0.08)) (h-2*(h*0.08)) (w-2*(w*0.08))*0.22
  stroke #000000/0.22 1
  circle w*0.22+(w-2*(w*0.22))*0.7 h*0.22+(h-2*(h*0.22))*0.6 (w-2*(w*0.22))*0.08
  fill #6b7176
end

list icon.general
  path w*0.18 h*0.18 w*0.18+(w-2*(w*0.18))-(w-2*(w*0.18))*0.3 h*0.18 w*0.18+(w-2*(w*0.18)) h*0.18+(w-2*(w*0.18))*0.3 w*0.18+(w-2*(w*0.18)) h*0.18+(h-2*(h*0.18)) w*0.18 h*0.18+(h-2*(h*0.18)) close
  fill #ffffff
  stroke #000000/0.35 1
end

list icon.loginItems
  path w*0.18 h*0.18 w*0.18+(w-2*(w*0.18))-(w-2*(w*0.18))*0.3 h*0.18 w*0.18+(w-2*(w*0.18)) h*0.18+(w-2*(w*0.18))*0.3 w*0.18+(w-2*(w*0.18)) h*0.18+(h-2*(h*0.18)) w*0.18 h*0.18+(h-2*(h*0.18)) close
  fill #ffffff
  stroke #000000/0.35 1
  path w*0.18+(w-2*(w*0.18))*0.18 h*0.18+(h-2*(h*0.18))*(0.45+0.16*0) w*0.18+(w-2*(w*0.18))*0.82 h*0.18+(h-2*(h*0.18))*(0.45+0.16*0)
  stroke rgba(0.3, 0.5, 0.85, 0.8) 1.5
  path w*0.18+(w-2*(w*0.18))*0.18 h*0.18+(h-2*(h*0.18))*(0.45+0.16*1) w*0.18+(w-2*(w*0.18))*0.82 h*0.18+(h-2*(h*0.18))*(0.45+0.16*1)
  stroke rgba(0.3, 0.5, 0.85, 0.8) 1.5
  path w*0.18+(w-2*(w*0.18))*0.18 h*0.18+(h-2*(h*0.18))*(0.45+0.16*2) w*0.18+(w-2*(w*0.18))*0.82 h*0.18+(h-2*(h*0.18))*(0.45+0.16*2)
  stroke rgba(0.3, 0.5, 0.85, 0.8) 1.5
end

list icon.myAccount
  circle w*0.2+(w-2*(w*0.2))/2 h*0.2+(h-2*(h*0.2))*0.3 (w-2*(w*0.2))*0.22
  fill #5b6168
  path w*0.2+(w-2*(w*0.2))*0.1 h*0.2+(h-2*(h*0.2)) arc w*0.2+(w-2*(w*0.2))/2 h*0.2+(h-2*(h*0.2))*0.95 (w-2*(w*0.2))*0.4 pi 2*pi close
  fill #5b6168
end

list icon.universalAccess
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2
  fill linear 0 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2 0 h*0.08+(h-2*(h*0.08))/2+(w-2*(w*0.08))/2 stops 0 shift(#2f6fd0, 0.3) 1 shift(#2f6fd0, -0.12)
  stroke #000000/0.25 1
  push
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2-0.5
  clip
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.2 (w-2*(w*0.08))/2*0.8
  fill radial w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.5 0 w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.4 (w-2*(w*0.08))/2 stops 0 #ffffff/0.6 1 #ffffff/0
  pop
  circle w*0.2+(w-2*(w*0.2))/2 h*0.2+(h-2*(h*0.2))*0.3 (w-2*(w*0.2))*0.22
  fill #ffffff
  path w*0.2+(w-2*(w*0.2))*0.1 h*0.2+(h-2*(h*0.2)) arc w*0.2+(w-2*(w*0.2))/2 h*0.2+(h-2*(h*0.2))*0.95 (w-2*(w*0.2))*0.4 pi 2*pi close
  fill #ffffff
end

list icon.accounts
  circle -w*0.12+w*0.2+(w-2*(w*0.2))/2 h*0.2+(h-2*(h*0.2))*0.3 (w-2*(w*0.2))*0.22
  fill #5b6168
  path -w*0.12+w*0.2+(w-2*(w*0.2))*0.1 h*0.2+(h-2*(h*0.2)) arc -w*0.12+w*0.2+(w-2*(w*0.2))/2 h*0.2+(h-2*(h*0.2))*0.95 (w-2*(w*0.2))*0.4 pi 2*pi close
  fill #5b6168
  circle w*0.16+w*0.9*0.2+(w*0.9-2*(w*0.9*0.2))/2 h*0.05+h*0.95*0.2+(h*0.95-2*(h*0.95*0.2))*0.3 (w*0.9-2*(w*0.9*0.2))*0.22
  fill #5b6168
  path w*0.16+w*0.9*0.2+(w*0.9-2*(w*0.9*0.2))*0.1 h*0.05+h*0.95*0.2+(h*0.95-2*(h*0.95*0.2)) arc w*0.16+w*0.9*0.2+(w*0.9-2*(w*0.9*0.2))/2 h*0.05+h*0.95*0.2+(h*0.95-2*(h*0.95*0.2))*0.95 (w*0.9-2*(w*0.9*0.2))*0.4 pi 2*pi close
  fill #5b6168
end

list icon.screenEffects
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2
  fill linear 0 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2 0 h*0.08+(h-2*(h*0.08))/2+(w-2*(w*0.08))/2 stops 0 shift(#2aa8a0, 0.3) 1 shift(#2aa8a0, -0.12)
  stroke #000000/0.25 1
  push
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2-0.5
  clip
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.2 (w-2*(w*0.08))/2*0.8
  fill radial w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.5 0 w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.4 (w-2*(w*0.08))/2 stops 0 #ffffff/0.6 1 #ffffff/0
  pop
  arc w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))*0.22 0 1.6*pi
  stroke #ffffff/0.85 2
  arc w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))*0.34 pi 2.6*pi
  stroke #ffffff/0.85 2
end

list icon.cdsDvds
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2
  fill linear 0 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2 0 h*0.08+(h-2*(h*0.08))/2+(w-2*(w*0.08))/2 stops 0 shift(#c8ccd0, 0.3) 1 shift(#c8ccd0, -0.12)
  stroke #000000/0.25 1
  push
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2-0.5
  clip
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.2 (w-2*(w*0.08))/2*0.8
  fill radial w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.5 0 w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.4 (w-2*(w*0.08))/2 stops 0 #ffffff/0.6 1 #ffffff/0
  pop
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))*0.12
  fill #ffffff/0.9
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))*0.32
  stroke rgba(0.4, 0.55, 0.85, 0.5) 4
end

list icon.energySaver
  circle w*0.2+(w-2*(w*0.2))/2 h*0.2+(h-2*(h*0.2))*0.4 (w-2*(w*0.2))*0.4
  fill #ffe14d
  stroke rgba(0.6, 0.5, 0, 0.5) 1
  rect w*0.2+(w-2*(w*0.2))*0.36 h*0.2+(h-2*(h*0.2))*0.72 (w-2*(w*0.2))*0.28 (h-2*(h*0.2))*0.2
  fill #9a9a9a
end

list icon.keyboard
  rect w*0.08 h*0.08 (w-2*(w*0.08)) (h-2*(h*0.08)) (w-2*(w*0.08))*0.22
  fill vertical stops 0 #f2f3f4 1 #c3c7cb
  # the gloss fills the whole tile: its capsule joins the kept path (HANDOFF §2.67)
  and rect w*0.08+1 h*0.08+1 (w-2*(w*0.08))-2 (h-2*(h*0.08))*0.42 ((w-2*(w*0.08))-2)*0.22
  fill linear 0 h*0.08+1 0 h*0.08+1+(h-2*(h*0.08))*0.42 stops 0 #ffffff/0.7 1 #ffffff/0.05
  rect w*0.08 h*0.08 (w-2*(w*0.08)) (h-2*(h*0.08)) (w-2*(w*0.08))*0.22
  stroke #000000/0.22 1
  rect w*0.22+0*(w-2*(w*0.22))*0.2 h*0.22+0*(h-2*(h*0.22))*0.34 (w-2*(w*0.22))*0.15 (h-2*(h*0.22))*0.22
  fill #000000/0.5
  rect w*0.22+1*(w-2*(w*0.22))*0.2 h*0.22+0*(h-2*(h*0.22))*0.34 (w-2*(w*0.22))*0.15 (h-2*(h*0.22))*0.22
  fill #000000/0.5
  rect w*0.22+2*(w-2*(w*0.22))*0.2 h*0.22+0*(h-2*(h*0.22))*0.34 (w-2*(w*0.22))*0.15 (h-2*(h*0.22))*0.22
  fill #000000/0.5
  rect w*0.22+3*(w-2*(w*0.22))*0.2 h*0.22+0*(h-2*(h*0.22))*0.34 (w-2*(w*0.22))*0.15 (h-2*(h*0.22))*0.22
  fill #000000/0.5
  rect w*0.22+4*(w-2*(w*0.22))*0.2 h*0.22+0*(h-2*(h*0.22))*0.34 (w-2*(w*0.22))*0.15 (h-2*(h*0.22))*0.22
  fill #000000/0.5
  rect w*0.22+0*(w-2*(w*0.22))*0.2 h*0.22+1*(h-2*(h*0.22))*0.34 (w-2*(w*0.22))*0.15 (h-2*(h*0.22))*0.22
  fill #000000/0.5
  rect w*0.22+1*(w-2*(w*0.22))*0.2 h*0.22+1*(h-2*(h*0.22))*0.34 (w-2*(w*0.22))*0.15 (h-2*(h*0.22))*0.22
  fill #000000/0.5
  rect w*0.22+2*(w-2*(w*0.22))*0.2 h*0.22+1*(h-2*(h*0.22))*0.34 (w-2*(w*0.22))*0.15 (h-2*(h*0.22))*0.22
  fill #000000/0.5
  rect w*0.22+3*(w-2*(w*0.22))*0.2 h*0.22+1*(h-2*(h*0.22))*0.34 (w-2*(w*0.22))*0.15 (h-2*(h*0.22))*0.22
  fill #000000/0.5
  rect w*0.22+4*(w-2*(w*0.22))*0.2 h*0.22+1*(h-2*(h*0.22))*0.34 (w-2*(w*0.22))*0.15 (h-2*(h*0.22))*0.22
  fill #000000/0.5
  rect w*0.22+0*(w-2*(w*0.22))*0.2 h*0.22+2*(h-2*(h*0.22))*0.34 (w-2*(w*0.22))*0.15 (h-2*(h*0.22))*0.22
  fill #000000/0.5
  rect w*0.22+1*(w-2*(w*0.22))*0.2 h*0.22+2*(h-2*(h*0.22))*0.34 (w-2*(w*0.22))*0.15 (h-2*(h*0.22))*0.22
  fill #000000/0.5
  rect w*0.22+2*(w-2*(w*0.22))*0.2 h*0.22+2*(h-2*(h*0.22))*0.34 (w-2*(w*0.22))*0.15 (h-2*(h*0.22))*0.22
  fill #000000/0.5
  rect w*0.22+3*(w-2*(w*0.22))*0.2 h*0.22+2*(h-2*(h*0.22))*0.34 (w-2*(w*0.22))*0.15 (h-2*(h*0.22))*0.22
  fill #000000/0.5
  rect w*0.22+4*(w-2*(w*0.22))*0.2 h*0.22+2*(h-2*(h*0.22))*0.34 (w-2*(w*0.22))*0.15 (h-2*(h*0.22))*0.22
  fill #000000/0.5
end

list icon.mouse
  rect w*0.26 h*0.26 (w-2*(w*0.26)) (h-2*(h*0.26)) (w-2*(w*0.26))/2
  fill vertical stops 0 #ffffff 1 #cfd3d7
  stroke #000000/0.3 1
  path w*0.26+(w-2*(w*0.26))/2 h*0.26+2 w*0.26+(w-2*(w*0.26))/2 h*0.26+(h-2*(h*0.26))*0.4
  stroke #000000/0.3 1
end

list icon.sharing
  path w*0.16 h*0.16+(h-2*(h*0.16))*0.2 w*0.16+(w-2*(w*0.16))*0.4 h*0.16+(h-2*(h*0.16))*0.2 w*0.16+(w-2*(w*0.16))*0.5 h*0.16+(h-2*(h*0.16))*0.34 w*0.16+(w-2*(w*0.16)) h*0.16+(h-2*(h*0.16))*0.34 w*0.16+(w-2*(w*0.16)) h*0.16+(h-2*(h*0.16))*0.85 w*0.16 h*0.16+(h-2*(h*0.16))*0.85 close
  fill linear 0 h*0.16 0 h*0.16+(h-2*(h*0.16)) stops 0 #9cc6f4 1 #4f86d6
end

list icon.dateTime
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2
  fill linear 0 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2 0 h*0.08+(h-2*(h*0.08))/2+(w-2*(w*0.08))/2 stops 0 shift(#f3f4f5, 0.3) 1 shift(#f3f4f5, -0.12)
  stroke #000000/0.25 1
  push
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2-0.5
  clip
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.2 (w-2*(w*0.08))/2*0.8
  fill radial w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.5 0 w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.4 (w-2*(w*0.08))/2 stops 0 #ffffff/0.6 1 #ffffff/0
  pop
  path w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(h-2*(h*0.08))*0.3
  stroke #000000/0.7 1.6
  path w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 w*0.08+(w-2*(w*0.08))/2+(w-2*(w*0.08))*0.22 h*0.08+(h-2*(h*0.08))/2
  stroke #000000/0.7 1.6
end

list icon.softwareUpdate
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2
  fill linear 0 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2 0 h*0.08+(h-2*(h*0.08))/2+(w-2*(w*0.08))/2 stops 0 shift(#2f6fd0, 0.3) 1 shift(#2f6fd0, -0.12)
  stroke #000000/0.25 1
  push
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))/2-0.5
  clip
  circle w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.2 (w-2*(w*0.08))/2*0.8
  fill radial w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.5 0 w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2-(w-2*(w*0.08))/2*0.4 (w-2*(w*0.08))/2 stops 0 #ffffff/0.6 1 #ffffff/0
  pop
  arc w*0.08+(w-2*(w*0.08))/2 h*0.08+(h-2*(h*0.08))/2 (w-2*(w*0.08))*0.26 -0.4*pi 1.1*pi
  stroke #ffffff/0.95 2.4
  path w*0.08+(w-2*(w*0.08))/2+(w-2*(w*0.08))*0.26 h*0.08+(h-2*(h*0.08))/2-(h-2*(h*0.08))*0.02 w*0.08+(w-2*(w*0.08))/2+(w-2*(w*0.08))*0.16 h*0.08+(h-2*(h*0.08))/2-(h-2*(h*0.08))*0.16 w*0.08+(w-2*(w*0.08))/2+(w-2*(w*0.08))*0.36 h*0.08+(h-2*(h*0.08))/2-(h-2*(h*0.08))*0.12 close
  fill #ffffff/0.95
end

# Islands (PHASE13 P13.7): three islands in a blue sea — Islands, Ebb, Shoals.
list icon.islands
  rect w*0.08 h*0.08 (w-2*(w*0.08)) (h-2*(h*0.08)) 4
  fill vertical stops 0 #9cc7f2 1 #2f66b8
  circle w*0.32 h*0.40 w*0.17
  fill #e8d9a8
  circle w*0.32 h*0.40 w*0.11
  fill #5aa24a
  circle w*0.68 h*0.36 w*0.13
  fill #e8d9a8
  circle w*0.68 h*0.36 w*0.08
  fill #5aa24a
  circle w*0.52 h*0.70 w*0.15
  fill #e8d9a8
  circle w*0.52 h*0.70 w*0.09
  fill #5aa24a
end
"""##

    static let file: DrawListFile = {
        do { return try DrawListFile(parsing: source) }
        catch { fatalError("the compiled Jaguar draw lists do not parse: \(error)") }
    }()
}
