// GENERATED by abyss/tools/gen-jaguar-lists.sh from themes/aqua/draw/*.dl (in name order)
// — do not edit. The compiled Jaguar draw lists, as ThemeTokens.jaguar is the
// compiled Jaguar tokens: what draws when no theme can be read, or one is
// refused. ThemeTests proves this is the file, byte for byte.

enum JaguarLists {
    static let source = ##"""
# Aqua — Jaguar's controls as draw lists (PHASE11 P11.4).
#
# Each list is the Swift recipe it replaced in de/aquadraw/Drawing.swift, op for
# op, and is proved byte-identical to it (Tests/AquaTests/DrawParityTests). Where
# the Swift did something odd, the list does it too, and says so: the gate for
# this pass is that nothing moves. Fixing what looks wrong is a change to the
# look, made later, on purpose, with the goldens updated.
#
# Coordinates are the widget's own (0 0 its top-left). See DrawList.swift for
# the format.

# The keyboard-focus halo, just outside a control. $radius is the control's.
list focusring
  rect -1.5 -1.5 w+3 h+3 $radius+1.5
  stroke fieldFocusRing 2.5
end

# Hairlines every 4 px, from 1.5 down (title bar, menu bar, toasts). $color.
list pinstripe
  rect 0 0 w h
  rules across 1.5 4 $color 1
end

# A traffic light: the rect is the drop's bounding square, $r its radius, $base
# its colour when the window is active.
list traffic
  circle $r $r $r
  when active fill linear 0 0 0 h stops 0 shift($base, 0.3) 0.5 $base 1 shift($base, -0.12)
  unless active fill linear 0 0 0 h stops 0 shift(trafficInactive, 0.3) 0.5 trafficInactive 1 shift(trafficInactive, -0.12)
  stroke trafficRim 0.75
  push
  circle $r $r $r-0.5
  clip
  circle $r $r-$r*0.18 $r*0.78
  fill radial $r $r-$r*0.45 0 $r $r-$r*0.35 $r*0.95 stops 0 #ffffff/0.85 0.6 #ffffff/0.25 1 #ffffff/0
  pop
  circle $r-$r*0.28 $r-$r*0.42 $r*0.16
  fill #ffffff/0.95
end

# The title bar's toolbar toggle.
list pill
  rect 0 0 w h h/2
  stroke #000000/0.3 1
end

# The white gel push button.
list button
  rect 0 0 w h h/2
  unless pressed fill vertical stops 0 buttonWhiteTop 1 buttonWhiteBottom
  when pressed fill vertical stops 0 shift(buttonWhiteTop, -0.08) 1 shift(buttonWhiteBottom, -0.08)
  stroke buttonWhiteBorder 1
  rect 1.5 1.5 w-3 h*0.45 h*0.45/2
  fill linear 0 1.5 0 1.5+h*0.45 stops 0 #ffffff/0.75 1 #ffffff/0.05
  text $label w/2 h/2 center color=buttonTextOnWhite
end

# The default (blue gel) push button.
list button.default
  rect 0 0 w h h/2
  unless pressed fill vertical stops 0 buttonBlueTop 0.5 buttonBlueMid 1 buttonBlueBottom
  when pressed fill vertical stops 0 shift(buttonBlueTop, -0.08) 0.5 shift(buttonBlueMid, -0.08) 1 shift(buttonBlueBottom, -0.08)
  stroke buttonBlueBorder 1
  rect 1.5 1.5 w-3 h*0.45 h*0.45/2
  fill linear 0 1.5 0 1.5+h*0.45 stops 0 #ffffff/0.75 1 #ffffff/0.05
  text $label w/2 h/2 center color=buttonTextOnBlue
end

# A text field: the label is its text, the placeholder shows when that is
# empty, and focused means it has the caret.
list textfield
  when focused rect -1.5 -1.5 w+3 h+3 4.5
  when focused stroke fieldFocusRing 2.5
  rect 0 0 w h 3
  fill fieldBackground
  innershadow fieldInsetShadow 4 5
  stroke fieldBorder 1
  push
  rect 4 0 w-8 h
  clip
  text $label 6 h/2+@fontSize*0.35 left baseline color=fieldText placeholder=fieldPlaceholder
  when focused path 6+textw(@fontSize)+1 5 6+textw(@fontSize)+1 h-5
  when focused stroke fieldCaret 1
  pop
end

# A checkbox; selected is checked.
#
# Checked, the gloss gradient fills the WHOLE box, not the 42% capsule it was
# drawn for: the Swift filled the body with fill_preserve and then added the
# capsule to the path it had kept, so the gloss filled both — `and`, below. The
# one-byte difference between "body" and "body and capsule" is why `and` exists.
# That is how it has always looked, so that is what this draws.
list checkbox
  rect 0 0 w h 3
  unless selected fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  unless selected innershadow controlInsetShadow 3 4
  unless selected stroke controlBorder 1
  when selected fill vertical stops 0 buttonBlueTop 0.5 buttonBlueMid 1 buttonBlueBottom
  when selected and rect 1 1 w-2 h*0.42 2
  when selected fill linear 0 1 0 1+h*0.42 stops 0 #ffffff/0.6 1 #ffffff/0.05
  when selected rect 0 0 w h 3
  when selected stroke buttonBlueBorder 1
  when selected path w*0.24 h*0.52 w*0.43 h*0.72 w*0.78 h*0.28
  when selected stroke controlGlyph 1.8 round
end

# A radio button: the rect is its bounding square, $r its radius.
list radio
  circle $r $r $r
  unless selected fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  when selected fill vertical stops 0 buttonBlueTop 0.5 buttonBlueMid 1 buttonBlueBottom
  unless selected stroke controlBorder 1
  when selected stroke buttonBlueBorder 1
  circle $r $r-$r*0.35 $r*0.62
  unless selected fill linear 0 0 0 $r stops 0 #ffffff/0.7 1 #ffffff/0
  when selected fill linear 0 0 0 $r stops 0 #ffffff/0.5 1 #ffffff/0
  when selected circle $r $r $r*0.34
  when selected fill controlGlyph
end

# A horizontal slider; the rect is the whole track, $thumb the thumb's centre.
list slider
  rect 0 (h-5)/2 w 5 5/2
  fill sliderTrack
  push
  clip
  rect 0 (h-5)/2 w 1.5
  fill sliderTrackEdge
  pop
  rect 0 (h-5)/2 w 5 5/2
  stroke controlBorder/0.6 1
  circle $thumb h/2 8
  fill vertical stops 0 controlWhiteTop 1 #c8c8c8
  stroke controlBorder 1
  circle $thumb h/2-8*0.3 8*0.6
  fill linear 0 h/2-8 0 h/2 stops 0 #ffffff/0.85 1 #ffffff/0
end

# A pop-up button: a white well with a blue cap on the right.
#
# The cap's gloss, like the checkbox's, fills the whole cap (fill_preserve).
list popup
  rect 0 0 w h 4
  fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  innershadow controlInsetShadow 3 4
  stroke controlBorder 1
  push
  clip
  rect w-h 0 h h
  fill vertical stops 0 buttonBlueTop 0.5 buttonBlueMid 1 buttonBlueBottom
  and rect w-h 1 h h*0.42
  fill linear 0 1 0 1+h*0.42 stops 0 #ffffff/0.5 1 #ffffff/0.02
  pop
  path w-h+0.5 1 w-h+0.5 h-1
  stroke buttonBlueBorder 1
  path w-h+h/2-3 h/2-2.5 w-h+h/2 h/2-5 w-h+h/2+3 h/2-2.5
  stroke controlGlyph 1.3 round
  path w-h+h/2-3 h/2+2.5 w-h+h/2 h/2+5 w-h+h/2+3 h/2+2.5
  stroke controlGlyph 1.3 round
  text $label (w-h)/2 h/2 center color=fieldText
  rect 0 0 w h 4
  stroke controlBorder 1
end

# A determinate progress bar. $fill is how far the blue runs (0 for none).
list progress
  rect 0 0 w h h/2
  fill progressTrack
  push
  clip
  rect 0 0 w 1.5
  fill controlInsetShadow
  pop
  push
  rect 0 0 w h h/2
  clip
  rect 0 0 $fill h
  fill vertical stops 0 buttonBlueTop 0.5 buttonBlueMid 1 buttonBlueBottom
  clip
  rect 0 0 w h
  rules slant -h 9 $fill #ffffff/0.2 3.5
  pop
  rect 0 0 w h h/2
  stroke controlBorder 1
end

# A scrollbar's channel.
#
# The inset shadow meant for the leading edge darkens the WHOLE channel by 10%:
# the Swift added the edge's rectangle to the gradient's kept path and filled
# both. Which edge it meant (left when vertical, top when not) cannot be seen
# under the wash, so this is one list for both.
list scrolltrack
  rect 0 0 w h
  fill vertical stops 0 #dedede 1 #eaeaea
  and rect 0 0 1.5 h
  fill #000000/0.1
  rect 0.5 0.5 w-1 h-1
  stroke controlBorder/0.55 1
end

# The blue gel thumb. Its gloss fills the whole thumb (fill_preserve).
list scrollthumb
  rect 0 0 w h min(w,h)/2
  fill vertical stops 0 buttonBlueTop 0.5 buttonBlueMid 1 buttonBlueBottom
  and rect 1.5 1.5 w-3 h*0.42 min(w-3,h*0.42)/2
  fill linear 0 1.5 0 1.5+h*0.42 stops 0 #ffffff/0.65 1 #ffffff/0.05
  rect 0 0 w h min(w,h)/2
  stroke buttonBlueBorder 1
end

# The scrollbar's arrow buttons; disabled when there is no travel left.
list scrollarrow.up
  rect 0 0 w h 2
  fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  innershadow controlInsetShadow 3 4
  stroke controlBorder 1
  path w/2 h/2-min(w,h)*0.26 w/2+min(w,h)*0.26 h/2+min(w,h)*0.26 w/2-min(w,h)*0.26 h/2+min(w,h)*0.26 close
  unless disabled fill buttonBlueMid
  when disabled fill controlBorder
end

list scrollarrow.down
  rect 0 0 w h 2
  fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  innershadow controlInsetShadow 3 4
  stroke controlBorder 1
  path w/2 h/2+min(w,h)*0.26 w/2+min(w,h)*0.26 h/2-min(w,h)*0.26 w/2-min(w,h)*0.26 h/2-min(w,h)*0.26 close
  unless disabled fill buttonBlueMid
  when disabled fill controlBorder
end

list scrollarrow.left
  rect 0 0 w h 2
  fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  innershadow controlInsetShadow 3 4
  stroke controlBorder 1
  path w/2-min(w,h)*0.26 h/2 w/2+min(w,h)*0.26 h/2-min(w,h)*0.26 w/2+min(w,h)*0.26 h/2+min(w,h)*0.26 close
  unless disabled fill buttonBlueMid
  when disabled fill controlBorder
end

list scrollarrow.right
  rect 0 0 w h 2
  fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  innershadow controlInsetShadow 3 4
  stroke controlBorder 1
  path w/2+min(w,h)*0.26 h/2 w/2-min(w,h)*0.26 h/2-min(w,h)*0.26 w/2-min(w,h)*0.26 h/2+min(w,h)*0.26 close
  unless disabled fill buttonBlueMid
  when disabled fill controlBorder
end

# A segmented control is drawn in passes, because a list cannot iterate over
# its segments: each segment's body, the strip's gloss, the dividers, the
# frame, then each label. Every pass's rect is the whole control; $x and $w
# are one segment's offset and width.
list segmented.segment
  rect 0 0 w h 4
  clip
  rect $x 0 $w h
  unless selected fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  when selected fill vertical stops 0 buttonBlueTop 0.5 buttonBlueMid 1 buttonBlueBottom
end

list segmented.gloss
  rect 0 0 w h 4
  clip
  rect 0 0 w h*0.45
  fill linear 0 0 0 h*0.45 stops 0 #ffffff/0.55 1 #ffffff/0.03
end

list segmented.divider
  path $x+0.5 1 $x+0.5 h-1
  stroke controlBorder/0.55 1
end

list segmented.frame
  rect 0 0 w h 4
  stroke controlBorder 1
end

list segmented.label
  unless selected text $label $x+$w/2 h/2 center color=fieldText
  when selected text $label $x+$w/2 h/2 center color=buttonTextOnBlue
end

# A tab view's content pane.
list tabpane
  rect 0 0 w h 6
  fill tabPaneBackground
  stroke tabBorder 1
end

# A tab on the pane's top edge; selected is the front one.
list tab
  rect 0 0 w h 6 top
  unless selected fill vertical stops 0 tabUnselectedTop 1 tabUnselectedBottom
  when selected fill vertical stops 0 tabSelectedTop 1 tabSelectedBottom
  stroke tabBorder 1
  text $label w/2 h/2+0.5 center color=tabText
end

# A titled group box: the title is notched into its top-left.
list groupbox
  rect 0 0 w h 5
  stroke groupBoxBorder 1
  rect 10 -6 textw(11)+8 12
  fill contentBackground
  text $label 14 4 left baseline size=11 color=controlLabel/0.75
end

# A list view's paper, its alternate-row stripe, and its frame (the scroll
# demo's list; the Finder's list view).
list listview
  rect 0 0 w h
  fill listBackground
end

list listview.stripe
  rect 0 0 w h
  fill listStripe
end

list listview.frame
  rect 0.5 0.5 w-1 h-1
  stroke controlBorder 1
end

# The selected tab merges into its pane: the pane's border under it is
# painted out. The rect is the tab; $pane is the pane's top, from the tab's.
list tab.merge
  rect 1 $pane-1 w-2 2
  fill tabPaneBackground
end

# A sheet. The window body under the title bar dims as it comes out
# ($progress 0…1); the panel hangs from the title bar with a soft shadow.
list sheet.dim
  rect 0 0 w h
  fill fade(sheetDim, $progress)
end

list sheet
  rect 0 2 w h 8 bottom
  fill sheetShadow
  rect 0 0 w h 8 bottom
  fill sheetBackground
  stroke windowBorder 1
end

# A pop-up menu: the paper, and the frame drawn over the items last. The rect
# is the whole menu surface.
list menu
  rect 0.5 0.5 w-1 h-1 5
  fill menuBackground
end

list menu.frame
  rect 0.5 0.5 w-1 h-1 5
  stroke menuBorder 1
end

# A separator: the rect is one pixel-snapped line across the menu.
list menu.separator
  rect 1 0 w-2 h
  fill menuSeparator
end

# An item's parts; the rect is the item's row across the menu, $color the
# colour its text is drawn in (on the highlight, enabled, or not).
list menu.highlight
  rect 3 0 w-6 h 3
  fill menuHighlight
end

list menu.check
  path 8 h/2+1 8+3 h/2+4 8+8 h/2-4
  stroke $color 1.6 round
end

list menu.submenu
  path w-@menu.rightInset-5 h/2-4.5 w-@menu.rightInset h/2 w-@menu.rightInset-5 h/2+4.5 close
  fill $color
end

# System Preferences' toolbar: its band, the separator along its foot, and the
# dotted divider after Show All ($x its position).
#
# The band's rectangle is stroked in the separator's colour along with the
# separator line, and so is outlined: the gradient was filled with
# fill_preserve and the line added to the kept path (HANDOFF §2.67).
list prefs.toolbar
  rect 0 0 w h
  fill vertical stops 0 prefsToolbarTop 1 prefsToolbarBottom
  and path 0 h-0.5 w h-0.5
  stroke separator 1
end

list prefs.toolbar.divider
  path $x 10 $x h-10
  stroke toolbarSeparator 1 dash=1,2
end

# A selected icon's name, on the highlight (the Finder's icon view, the
# desktop); the rect is the label's, padded.
list iconlabel.selected
  rect 0 0 w h 3
  fill menuHighlight
end

# A list view's selected row.
list listview.selection
  rect 0 0 w h
  fill menuHighlight
end
# Aqua — the Finder's window paint (PHASE11 P11.5): toolbar, list header,
# status bar, selection, the rename field. Its item icons are P11.8's, its
# text the toolkit's.

# The toolbar band, with the separator along its foot.
list finder.toolbar
  rect 0 0 w h
  fill vertical stops 0 toolbarTop 1 toolbarBottom
  path 0 h-0.5 w h-0.5
  stroke separator 1
end

# The Back control: a white gel capsule with a left-pointing glyph. Pressed
# while held; disabled at the top of the history.
list finder.back
  rect 0 0 w h 5
  when pressed fill vertical stops 0 controlPressedTop 1 controlPressedBottom
  unless pressed fill vertical stops 0 controlWhiteTop 1 controlWhiteBottom
  unless disabled stroke controlBorder/1 1
  when disabled stroke controlBorder/0.5 1
  path w/2-4 h/2 w/2+3 h/2-5 w/2+3 h/2+5 close
  unless disabled fill toolbarGlyph
  when disabled fill toolbarGlyph/0.35
end

# The glyphs on the icon/list view switch (a segmented control, drawn first):
# four tiles on the left segment, three lines on the right. Selected is the
# list view; each glyph is white on the chosen segment.
list finder.viewswitch
  rect w/2/2-4-2/2 h/2-4-2/2 4 4
  and rect w/2/2-4-2/2+(4+2) h/2-4-2/2 4 4
  and rect w/2/2-4-2/2 h/2-4-2/2+(4+2) 4 4
  and rect w/2/2-4-2/2+(4+2) h/2-4-2/2+(4+2) 4 4
  unless selected fill controlGlyph
  when selected fill segmentGlyph
  path w/2+w/2/2-5.5 h/2-4 w/2+w/2/2-5.5+11 h/2-4
  and path w/2+w/2/2-5.5 h/2-4+4 w/2+w/2/2-5.5+11 h/2-4+4
  and path w/2+w/2/2-5.5 h/2-4+8 w/2+w/2/2-5.5+11 h/2-4+8
  when selected stroke controlGlyph 1.6
  unless selected stroke segmentGlyph 1.6
end

# The list view's column header, its foot, and a divider at column $x.
list finder.header
  rect 0 0 w h
  fill vertical stops 0 listHeaderTop 1 listHeaderBottom
  path 0 h-0.5 w h-0.5
  stroke separator 1
end

list finder.header.divider
  path $x+0.5 2 $x+0.5 h-2
  stroke separator 1
end

# The hairline along the top of the item well; the rect is one line high.
list finder.welledge
  path 0 0.5 w 0.5
  stroke separator 1
end

# A selected icon's soft blue wash; the rect is the icon.
list finder.selection
  rect -3 -3 w+6 h+6 6
  fill menuHighlight/0.22
end

# The inline rename field: a white well in the focus ring. Selected when part
# of the name is selected: $sel is that run's width. Its text is drawn next,
# then the caret, at $caret.
list finder.namefield
  rect 0 0 w h
  fill fieldBackground
  rect -1.5 -1.5 w+3 h+3 2+1.5
  stroke fieldFocusRing 2.5
  rect 0.5 0.5 w-1 h-1
  stroke fieldBorder 1
  when selected rect 4-1 2 $sel+2 h-4
  when selected fill menuHighlight
end

list finder.namefield.caret
  rect $caret 2 1 h-4
  fill fieldCaret
end

# The status bar, with the separator along its top.
list finder.status
  rect 0 0 w h
  fill vertical stops 0 statusBarTop 1 statusBarBottom
  path 0 0.5 w 0.5
  stroke separator 1
end
# Aqua — the installer's paint (PHASE11 P11.5). Its text is the toolkit's.

# The window body: Aqua's pale, the pinstripe along the top 40 px the way a
# Jaguar utility window wears it, and the separator under it.
list installer
  rect 0 0 w h
  fill contentBackground
  rect 0 0 w 40
  rules across 1.5 4 pinstripe 1
  rect 0 39.5 w 1
  fill separator
end

# A hub row: done, or (the .attention variant) still wanting an answer.
list installer.spoke
  rect 0 0 w h 6
  fill rowBackground
  stroke separator 1
end

list installer.spoke.attention
  rect 0 0 w h 6
  fill attentionBackground
  stroke separator 1
end

# A picker row, selected. Disabled is a disk that cannot be used: it is still
# shown, greyed, with its reason — never hidden.
list installer.row
  rect 0 0 w h
  unless disabled fill menuHighlight
  when disabled fill trafficInactive
end

# A control that is present but cannot be used.
list installer.veil
  rect 0 0 w h h/2
  fill disabledVeil
end
# Aqua — the desktop shell's paint: the menu bar, toasts, the Dock, the
# wallpaper (PHASE11 P11.5). Like aqua.dl, each list is the Swift it replaced,
# op for op, held to the golden gate; the text on these surfaces is still drawn
# by the toolkit's text calls until type comes by role (P11.7).

# The menu bar's background.
#
# The pinstripe's first hairline is stroked TOGETHER with the bar's outline:
# the gradient was filled with fill_preserve, so the bar's rectangle was still
# the path when the pinstripe began (HANDOFF §2.67). So the bar is outlined, 1 px,
# in the pinstripe's colour, and that is what `and` below reproduces.
list menubar
  rect 0 0 w h
  fill vertical stops 0 menuBarTop 1 menuBarBottom
  and path 0 1.5 w 1.5
  stroke menuBarBottom/0.5 1
  rect 0 0 w h
  rules across 5.5 4 menuBarBottom/0.5 1
  path 0 h-0.5 w h-0.5
  stroke menuBarBorder 1
end

# An open title's highlight; the rect is the title's slot, full height.
list menubar.highlight
  rect 0 0 w h
  fill menuHighlight
end

# The system menu's mark: an original water drop, a bulb under a point — not
# Apple's apple. Selected while its menu is open.
list menubar.system
  circle w/2 h*0.62 w*0.42
  and path w/2 h*0.08 w/2+w*0.42*0.92 h*0.62 w/2-w*0.42*0.92 h*0.62 close
  unless selected fill menuBarText
  when selected fill menuTextOnHighlight
end

# A notification toast's panel.
#
# There is no border: the Swift stroked toastBorder along a path the pinstripe
# had already stroked and so consumed — deleting that stroke moved no pixel.
# What outlines the panel is the pinstripe's first hairline, stroked with the
# kept outline (§2.67), clipped to the panel. toastBorder is a token nothing
# draws, until the look is changed on purpose.
list toast
  rect 1 2 w h @toast.corner
  fill toastShadow
  rect 0 0 w h @toast.corner
  push
  clip
  fill vertical stops 0 toastTop 1 toastBottom
  and path 0 1.5 w 1.5
  stroke toastPinstripe 1
  rect 0 0 w h
  rules across 5.5 4 toastPinstripe 1
  pop
end

# The drop that marks a toast as the system's, 13 × 13.
list toast.mark
  path w/2 0 curve w/2+w*0.55 h*0.45 w/2+w*0.5 h w/2 h curve w/2-w*0.5 h w/2-w*0.55 h*0.45 w/2 0 close
  fill systemMark
end

# The menu bar's volume item: a speaker, and one arc per third of the range —
# none when muted, which is the point of arcs rather than a fixed glyph. One
# list per level (a list cannot count); the toolkit picks by level. $color is
# the bar's text colour.
list status.volume.0
  path 0 h/2-h*0.18 w*0.32 h/2-h*0.18 w*0.32*2.1 0 w*0.32*2.1 h w*0.32 h/2+h*0.18 0 h/2+h*0.18 close
  fill $color
end

list status.volume.1
  path 0 h/2-h*0.18 w*0.32 h/2-h*0.18 w*0.32*2.1 0 w*0.32*2.1 h w*0.32 h/2+h*0.18 0 h/2+h*0.18 close
  fill $color
  arc w*0.32*2.1 h/2 w*(0.30+0.16*0) -0.9 0.9
  stroke $color 1.2
end

list status.volume.2
  path 0 h/2-h*0.18 w*0.32 h/2-h*0.18 w*0.32*2.1 0 w*0.32*2.1 h w*0.32 h/2+h*0.18 0 h/2+h*0.18 close
  fill $color
  arc w*0.32*2.1 h/2 w*(0.30+0.16*0) -0.9 0.9
  stroke $color 1.2
  arc w*0.32*2.1 h/2 w*(0.30+0.16*1) -0.9 0.9
  stroke $color 1.2
end

list status.volume.3
  path 0 h/2-h*0.18 w*0.32 h/2-h*0.18 w*0.32*2.1 0 w*0.32*2.1 h w*0.32 h/2+h*0.18 0 h/2+h*0.18 close
  fill $color
  arc w*0.32*2.1 h/2 w*(0.30+0.16*0) -0.9 0.9
  stroke $color 1.2
  arc w*0.32*2.1 h/2 w*(0.30+0.16*1) -0.9 0.9
  stroke $color 1.2
  arc w*0.32*2.1 h/2 w*(0.30+0.16*2) -0.9 0.9
  stroke $color 1.2
end

# The battery item: an outline, a terminal nub, a fill of $charge (0…1), and,
# active while charging, a bolt cut out of it. $color is the bar's text colour.
list status.battery
  rect 0.5 0.5 w-1 h-1
  stroke $color 1
  rect w h*0.3 1.5 h*0.4
  fill $color
  rect 2 2 (w-2*2)*$charge h-2*2
  fill $color
  when active path w*0.52 1 w*0.36 h*0.55 w*0.50 h*0.55 w*0.42 h-1 w*0.64 h*0.45 w*0.50 h*0.45 close
  when active fill statusGlyphCutout
end

# A desktop icon's selection: a translucent plate behind the icon. (Its label
# sits on iconlabel.selected, as a Finder icon's does — aqua.dl.)
list desktop.selection
  rect -3 -3 w+6 h+6 6
  fill menuHighlight/0.35
end

# The built-in "Aqua Blue" backdrop: a light sky top deepening to ocean blue,
# with a broad soft sheen high and left of centre. (A flat colour, gradient or
# picture chosen in desktop.ini is the person's, not the theme's, and is drawn
# by the toolkit.)
list wallpaper
  rect 0 0 w h
  fill vertical stops 0 desktopTop 0.55 desktopMiddle 1 desktopBottom
  fill radial w*0.42 h*0.30 max(w,h)*0.75 stops 0 desktopGlow 1 desktopGlow/0
end

# The Dock: its translucent shelf (the rect), the separator before the Trash
# ($x across the shelf), the running mark under a tile (its rect, 6 × 4), and
# the hovered tile's label plate.
list dock.shelf
  rect 0 0 w h h/4
  fill vertical stops 0 dockShelfTop 1 dockShelfBottom
  stroke dockShelfBorder 1
end

list dock.separator
  path $x 6 $x h-6
  stroke dockSeparator 1
end

list dock.running
  path 0 h w h w/2 0 close
  fill dockRunningMark
end

list dock.label
  rect 0 0 w h 5
  fill dockLabelBackground
end
"""##

    static let file: DrawListFile = {
        do { return try DrawListFile(parsing: source) }
        catch { fatalError("the compiled Jaguar draw lists do not parse: \(error)") }
    }()
}
