#!/bin/sh
# Regenerate de/aquadraw/JaguarLists.swift — the compiled copy of Aqua's draw
# lists, drawn with when no theme can be read (PHASE11 P11.4). ThemeTests fails
# when the two differ, naming this script.
set -eu
root=$(cd "$(dirname "$0")/../.." && pwd)
out="$root/de/aquadraw/JaguarLists.swift"
{
  echo '// GENERATED by abyss/tools/gen-jaguar-lists.sh from themes/aqua/draw/aqua.dl'
  echo '// — do not edit. The compiled Jaguar draw lists, as ThemeTokens.jaguar is the'
  echo '// compiled Jaguar tokens: what draws when no theme can be read, or one is'
  echo '// refused. ThemeTests proves this is the file, byte for byte.'
  echo
  echo 'enum JaguarLists {'
  echo '    static let source = ##"""'
  cat "$root/themes/aqua/draw/aqua.dl"
  echo '"""##'
  echo
  echo '    static let file: DrawListFile = {'
  echo '        do { return try DrawListFile(parsing: source) }'
  echo '        catch { fatalError("the compiled Jaguar draw lists do not parse: \(error)") }'
  echo '    }()'
  echo '}'
} > "$out"
echo "wrote $out"
