/* Generated by wayland-scanner 1.26.0 */

#ifndef ABYSS_WINDOW_V1_CLIENT_PROTOCOL_H
#define ABYSS_WINDOW_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_abyss_window_v1 The abyss_window_v1 protocol
 * window operations xdg-shell does not have
 *
 * @section page_desc_abyss_window_v1 Description
 *
 * xdg-shell lets a client ask to be moved, resized, maximized, minimized
 * and made fullscreen, and never to be sent behind other windows — the
 * depth gadget a window frame may carry (PHASE11.md P11.6). A client that
 * draws its own frame asks undertow here; a frame undertow draws for a
 * client acts directly.
 *
 * The compositor decides. A request is a request: a compositor may ignore
 * it, and a client must not assume its window moved.
 *
 * @section page_ifaces_abyss_window_v1 Interfaces
 * - @subpage page_iface_abyss_window_manager_v1 - window operations
 * @section page_copyright_abyss_window_v1 Copyright
 * <pre>
 *
 * AbyssBSD Swift DE. Same terms as the rest of the tree.
 * </pre>
 */
struct abyss_window_manager_v1;
struct xdg_toplevel;

#ifndef ABYSS_WINDOW_MANAGER_V1_INTERFACE
#define ABYSS_WINDOW_MANAGER_V1_INTERFACE
/**
 * @page page_iface_abyss_window_manager_v1 abyss_window_manager_v1
 * @section page_iface_abyss_window_manager_v1_desc Description
 *
 * A global with no events. Bind it, and ask.
 * @section page_iface_abyss_window_manager_v1_api API
 * See @ref iface_abyss_window_manager_v1.
 */
/**
 * @defgroup iface_abyss_window_manager_v1 The abyss_window_manager_v1 interface
 *
 * A global with no events. Bind it, and ask.
 */
extern const struct wl_interface abyss_window_manager_v1_interface;
#endif

#define ABYSS_WINDOW_MANAGER_V1_DESTROY 0
#define ABYSS_WINDOW_MANAGER_V1_LOWER 1


/**
 * @ingroup iface_abyss_window_manager_v1
 */
#define ABYSS_WINDOW_MANAGER_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_abyss_window_manager_v1
 */
#define ABYSS_WINDOW_MANAGER_V1_LOWER_SINCE_VERSION 1

/** @ingroup iface_abyss_window_manager_v1 */
static inline void
abyss_window_manager_v1_set_user_data(struct abyss_window_manager_v1 *abyss_window_manager_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) abyss_window_manager_v1, user_data);
}

/** @ingroup iface_abyss_window_manager_v1 */
static inline void *
abyss_window_manager_v1_get_user_data(struct abyss_window_manager_v1 *abyss_window_manager_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) abyss_window_manager_v1);
}

static inline uint32_t
abyss_window_manager_v1_get_version(struct abyss_window_manager_v1 *abyss_window_manager_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) abyss_window_manager_v1);
}

/**
 * @ingroup iface_abyss_window_manager_v1
 */
static inline void
abyss_window_manager_v1_destroy(struct abyss_window_manager_v1 *abyss_window_manager_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) abyss_window_manager_v1,
			 ABYSS_WINDOW_MANAGER_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) abyss_window_manager_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_abyss_window_manager_v1
 *
 * Put the toplevel behind every other window. If it had the keyboard,
 * the window now in front gets it: a window put away is not the one
 * being typed into. The toplevel must be one of this client's.
 */
static inline void
abyss_window_manager_v1_lower(struct abyss_window_manager_v1 *abyss_window_manager_v1, struct xdg_toplevel *toplevel)
{
	wl_proxy_marshal_flags((struct wl_proxy *) abyss_window_manager_v1,
			 ABYSS_WINDOW_MANAGER_V1_LOWER, NULL, wl_proxy_get_version((struct wl_proxy *) abyss_window_manager_v1), 0, toplevel);
}

#ifdef  __cplusplus
}
#endif

#endif
