/* Generated by wayland-scanner 1.26.0 */

#ifndef ABYSS_MENU_V1_CLIENT_PROTOCOL_H
#define ABYSS_MENU_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_abyss_menu_v1 The abyss_menu_v1 protocol
 * whose menus belong to which window
 *
 * @section page_desc_abyss_menu_v1 Description
 *
 * A global menu bar has to show the menus of the application whose window is
 * focused, and only the compositor knows which surface that is. An
 * application therefore tells the compositor, per surface, where its menus
 * are published; the compositor tells the menu bar — and nobody else — where
 * the focused surface's menus are whenever focus moves.
 *
 * The address is bound to a surface, by the client that owns the surface, on
 * the connection that proves it. Nothing here trusts an app_id.
 *
 * @section page_ifaces_abyss_menu_v1 Interfaces
 * - @subpage page_iface_abyss_menu_manager_v1 - publish where a surface's menus live
 * - @subpage page_iface_abyss_menubar_v1 - the menu bar's view of focus
 * @section page_copyright_abyss_menu_v1 Copyright
 * <pre>
 *
 * AbyssBSD Swift DE. PHASE10.md P10.3.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * </pre>
 */
struct abyss_menu_manager_v1;
struct abyss_menubar_v1;
struct wl_surface;

#ifndef ABYSS_MENU_MANAGER_V1_INTERFACE
#define ABYSS_MENU_MANAGER_V1_INTERFACE
/**
 * @page page_iface_abyss_menu_manager_v1 abyss_menu_manager_v1
 * @section page_iface_abyss_menu_manager_v1_desc Description
 *
 * Offered to every client.
 * @section page_iface_abyss_menu_manager_v1_api API
 * See @ref iface_abyss_menu_manager_v1.
 */
/**
 * @defgroup iface_abyss_menu_manager_v1 The abyss_menu_manager_v1 interface
 *
 * Offered to every client.
 */
extern const struct wl_interface abyss_menu_manager_v1_interface;
#endif
#ifndef ABYSS_MENUBAR_V1_INTERFACE
#define ABYSS_MENUBAR_V1_INTERFACE
/**
 * @page page_iface_abyss_menubar_v1 abyss_menubar_v1
 * @section page_iface_abyss_menubar_v1_desc Description
 *
 * Offered only to clients that connected to the compositor's privileged
 * socket (PHASE10 §6.1). It says which application is frontmost and where
 * its menus are, which is exactly what an ordinary client must not learn.
 * @section page_iface_abyss_menubar_v1_api API
 * See @ref iface_abyss_menubar_v1.
 */
/**
 * @defgroup iface_abyss_menubar_v1 The abyss_menubar_v1 interface
 *
 * Offered only to clients that connected to the compositor's privileged
 * socket (PHASE10 §6.1). It says which application is frontmost and where
 * its menus are, which is exactly what an ordinary client must not learn.
 */
extern const struct wl_interface abyss_menubar_v1_interface;
#endif

#define ABYSS_MENU_MANAGER_V1_DESTROY 0
#define ABYSS_MENU_MANAGER_V1_SET_ADDRESS 1


/**
 * @ingroup iface_abyss_menu_manager_v1
 */
#define ABYSS_MENU_MANAGER_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_abyss_menu_manager_v1
 */
#define ABYSS_MENU_MANAGER_V1_SET_ADDRESS_SINCE_VERSION 1

/** @ingroup iface_abyss_menu_manager_v1 */
static inline void
abyss_menu_manager_v1_set_user_data(struct abyss_menu_manager_v1 *abyss_menu_manager_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) abyss_menu_manager_v1, user_data);
}

/** @ingroup iface_abyss_menu_manager_v1 */
static inline void *
abyss_menu_manager_v1_get_user_data(struct abyss_menu_manager_v1 *abyss_menu_manager_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) abyss_menu_manager_v1);
}

static inline uint32_t
abyss_menu_manager_v1_get_version(struct abyss_menu_manager_v1 *abyss_menu_manager_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) abyss_menu_manager_v1);
}

/**
 * @ingroup iface_abyss_menu_manager_v1
 */
static inline void
abyss_menu_manager_v1_destroy(struct abyss_menu_manager_v1 *abyss_menu_manager_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) abyss_menu_manager_v1,
			 ABYSS_MENU_MANAGER_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) abyss_menu_manager_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_abyss_menu_manager_v1
 *
 * Set or replace the menu address of a surface this client owns. An
 * empty address withdraws it. The address is a CurrentIPC service name
 * (MenuWire, PHASE10 P10.2). It is forgotten when the surface is
 * destroyed.
 */
static inline void
abyss_menu_manager_v1_set_address(struct abyss_menu_manager_v1 *abyss_menu_manager_v1, struct wl_surface *surface, const char *address)
{
	wl_proxy_marshal_flags((struct wl_proxy *) abyss_menu_manager_v1,
			 ABYSS_MENU_MANAGER_V1_SET_ADDRESS, NULL, wl_proxy_get_version((struct wl_proxy *) abyss_menu_manager_v1), 0, surface, address);
}

#ifndef ABYSS_MENUBAR_V1_KIND_ENUM
#define ABYSS_MENUBAR_V1_KIND_ENUM
enum abyss_menubar_v1_kind {
	/**
	 * the focused window publishes no menus, or nothing is focused
	 */
	ABYSS_MENUBAR_V1_KIND_NONE = 0,
	/**
	 * a MenuWire service name
	 */
	ABYSS_MENUBAR_V1_KIND_ABYSS = 1,
	/**
	 * a GTK application's bus name and menu paths (P10.6)
	 */
	ABYSS_MENUBAR_V1_KIND_GTK = 2,
	/**
	 * a com.canonical.dbusmenu service and path (P10.7)
	 */
	ABYSS_MENUBAR_V1_KIND_DBUSMENU = 3,
};
#endif /* ABYSS_MENUBAR_V1_KIND_ENUM */

/**
 * @ingroup iface_abyss_menubar_v1
 * @struct abyss_menubar_v1_listener
 */
struct abyss_menubar_v1_listener {
	/**
	 * focus moved; here is where its menus are
	 *
	 * Sent once on bind, and again whenever keyboard focus moves to
	 * a different toplevel, or the focused toplevel's address changes.
	 * With kind none, address is empty.
	 */
	void (*focused)(void *data,
			struct abyss_menubar_v1 *abyss_menubar_v1,
			uint32_t kind,
			const char *address,
			const char *app_id);
};

/**
 * @ingroup iface_abyss_menubar_v1
 */
static inline int
abyss_menubar_v1_add_listener(struct abyss_menubar_v1 *abyss_menubar_v1,
			      const struct abyss_menubar_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) abyss_menubar_v1,
				     (void (**)(void)) listener, data);
}

#define ABYSS_MENUBAR_V1_DESTROY 0
#define ABYSS_MENUBAR_V1_FORCE_QUIT 1

/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_FOCUSED_SINCE_VERSION 1

/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_FORCE_QUIT_SINCE_VERSION 2

/** @ingroup iface_abyss_menubar_v1 */
static inline void
abyss_menubar_v1_set_user_data(struct abyss_menubar_v1 *abyss_menubar_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) abyss_menubar_v1, user_data);
}

/** @ingroup iface_abyss_menubar_v1 */
static inline void *
abyss_menubar_v1_get_user_data(struct abyss_menubar_v1 *abyss_menubar_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) abyss_menubar_v1);
}

static inline uint32_t
abyss_menubar_v1_get_version(struct abyss_menubar_v1 *abyss_menubar_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) abyss_menubar_v1);
}

/**
 * @ingroup iface_abyss_menubar_v1
 */
static inline void
abyss_menubar_v1_destroy(struct abyss_menubar_v1 *abyss_menubar_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) abyss_menubar_v1,
			 ABYSS_MENUBAR_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) abyss_menubar_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_abyss_menubar_v1
 *
 * Kill every client with a toplevel of this app_id. Only the compositor
 * knows which processes those are, and only the menu bar — on the
 * privileged socket — may ask (PHASE10 P10.8). The compositor never kills
 * itself.
 */
static inline void
abyss_menubar_v1_force_quit(struct abyss_menubar_v1 *abyss_menubar_v1, const char *app_id)
{
	wl_proxy_marshal_flags((struct wl_proxy *) abyss_menubar_v1,
			 ABYSS_MENUBAR_V1_FORCE_QUIT, NULL, wl_proxy_get_version((struct wl_proxy *) abyss_menubar_v1), 0, app_id);
}

#ifdef  __cplusplus
}
#endif

#endif
