/* Generated by wayland-scanner 1.26.0 */

#ifndef ABYSS_MENU_V1_CLIENT_PROTOCOL_H
#define ABYSS_MENU_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_abyss_menu_v1 The abyss_menu_v1 protocol
 * whose menus belong to which window
 *
 * @section page_desc_abyss_menu_v1 Description
 *
 * A global menu bar has to show the menus of the application whose window is
 * focused, and only the compositor knows which surface that is. An
 * application therefore tells the compositor, per surface, where its menus
 * are published; the compositor tells the menu bar — and nobody else — where
 * the focused surface's menus are whenever focus moves.
 *
 * The address is bound to a surface, by the client that owns the surface, on
 * the connection that proves it. Nothing here trusts an app_id.
 *
 * @section page_ifaces_abyss_menu_v1 Interfaces
 * - @subpage page_iface_abyss_menu_manager_v1 - publish where a surface's menus live
 * - @subpage page_iface_abyss_menubar_v1 - the menu bar's view of focus
 * @section page_copyright_abyss_menu_v1 Copyright
 * <pre>
 *
 * AbyssBSD Swift DE. PHASE10.md P10.3.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * </pre>
 */
struct abyss_menu_manager_v1;
struct abyss_menubar_v1;
struct wl_surface;

#ifndef ABYSS_MENU_MANAGER_V1_INTERFACE
#define ABYSS_MENU_MANAGER_V1_INTERFACE
/**
 * @page page_iface_abyss_menu_manager_v1 abyss_menu_manager_v1
 * @section page_iface_abyss_menu_manager_v1_desc Description
 *
 * Offered to every client.
 * @section page_iface_abyss_menu_manager_v1_api API
 * See @ref iface_abyss_menu_manager_v1.
 */
/**
 * @defgroup iface_abyss_menu_manager_v1 The abyss_menu_manager_v1 interface
 *
 * Offered to every client.
 */
extern const struct wl_interface abyss_menu_manager_v1_interface;
#endif
#ifndef ABYSS_MENUBAR_V1_INTERFACE
#define ABYSS_MENUBAR_V1_INTERFACE
/**
 * @page page_iface_abyss_menubar_v1 abyss_menubar_v1
 * @section page_iface_abyss_menubar_v1_desc Description
 *
 * Offered only to clients that connected to the compositor's privileged
 * socket (PHASE10 §6.1). It says which application is frontmost and where
 * its menus are, which is exactly what an ordinary client must not learn.
 * @section page_iface_abyss_menubar_v1_api API
 * See @ref iface_abyss_menubar_v1.
 */
/**
 * @defgroup iface_abyss_menubar_v1 The abyss_menubar_v1 interface
 *
 * Offered only to clients that connected to the compositor's privileged
 * socket (PHASE10 §6.1). It says which application is frontmost and where
 * its menus are, which is exactly what an ordinary client must not learn.
 */
extern const struct wl_interface abyss_menubar_v1_interface;
#endif

#define ABYSS_MENU_MANAGER_V1_DESTROY 0
#define ABYSS_MENU_MANAGER_V1_SET_ADDRESS 1


/**
 * @ingroup iface_abyss_menu_manager_v1
 */
#define ABYSS_MENU_MANAGER_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_abyss_menu_manager_v1
 */
#define ABYSS_MENU_MANAGER_V1_SET_ADDRESS_SINCE_VERSION 1

/** @ingroup iface_abyss_menu_manager_v1 */
static inline void
abyss_menu_manager_v1_set_user_data(struct abyss_menu_manager_v1 *abyss_menu_manager_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) abyss_menu_manager_v1, user_data);
}

/** @ingroup iface_abyss_menu_manager_v1 */
static inline void *
abyss_menu_manager_v1_get_user_data(struct abyss_menu_manager_v1 *abyss_menu_manager_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) abyss_menu_manager_v1);
}

static inline uint32_t
abyss_menu_manager_v1_get_version(struct abyss_menu_manager_v1 *abyss_menu_manager_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) abyss_menu_manager_v1);
}

/**
 * @ingroup iface_abyss_menu_manager_v1
 */
static inline void
abyss_menu_manager_v1_destroy(struct abyss_menu_manager_v1 *abyss_menu_manager_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) abyss_menu_manager_v1,
			 ABYSS_MENU_MANAGER_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) abyss_menu_manager_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_abyss_menu_manager_v1
 *
 * Set or replace the menu address of a surface this client owns. An
 * empty address withdraws it. The address is a CurrentIPC service name
 * (MenuWire, PHASE10 P10.2). It is forgotten when the surface is
 * destroyed.
 */
static inline void
abyss_menu_manager_v1_set_address(struct abyss_menu_manager_v1 *abyss_menu_manager_v1, struct wl_surface *surface, const char *address)
{
	wl_proxy_marshal_flags((struct wl_proxy *) abyss_menu_manager_v1,
			 ABYSS_MENU_MANAGER_V1_SET_ADDRESS, NULL, wl_proxy_get_version((struct wl_proxy *) abyss_menu_manager_v1), 0, surface, address);
}

#ifndef ABYSS_MENUBAR_V1_KIND_ENUM
#define ABYSS_MENUBAR_V1_KIND_ENUM
enum abyss_menubar_v1_kind {
	/**
	 * the focused window publishes no menus, or nothing is focused
	 */
	ABYSS_MENUBAR_V1_KIND_NONE = 0,
	/**
	 * a MenuWire service name
	 */
	ABYSS_MENUBAR_V1_KIND_ABYSS = 1,
	/**
	 * a GTK application's bus name and menu paths (P10.6)
	 */
	ABYSS_MENUBAR_V1_KIND_GTK = 2,
};
#endif /* ABYSS_MENUBAR_V1_KIND_ENUM */

/**
 * @ingroup iface_abyss_menubar_v1
 * @struct abyss_menubar_v1_listener
 */
struct abyss_menubar_v1_listener {
	/**
	 * focus moved; here is where its menus are
	 *
	 * Sent once on bind, and again whenever keyboard focus moves to
	 * a different toplevel, or the focused toplevel's address changes.
	 * With kind none, address is empty.
	 */
	void (*focused)(void *data,
			struct abyss_menubar_v1 *abyss_menubar_v1,
			uint32_t kind,
			const char *address,
			const char *app_id);
	/**
	 * a display shows an island
	 *
	 * Sent for every display on bind, and again whenever a display's
	 * island changes. is_main is 1 for the display the menu bar is on.
	 * @param count islands that display has
	 * @since 3
	 */
	void (*island)(void *data,
		       struct abyss_menubar_v1 *abyss_menubar_v1,
		       const char *display,
		       uint32_t island,
		       const char *name,
		       uint32_t count,
		       uint32_t is_main);
	/**
	 * @param id this window, for activate_window
	 * @since 3
	 */
	void (*window)(void *data,
		       struct abyss_menubar_v1 *abyss_menubar_v1,
		       uint32_t id,
		       const char *display,
		       uint32_t island,
		       const char *app_id,
		       const char *title);
	/**
	 * the list is complete
	 *
	 * With every island's name, in order, separated by tabs: island
	 * 1's first. A name the person never set is the number.
	 * @since 3
	 */
	void (*islands_done)(void *data,
			     struct abyss_menubar_v1 *abyss_menubar_v1,
			     const char *names);
	/**
	 * a shoal, sent with the island list
	 *
	 * Sent after the window events of a list_islands answer, before
	 * islands_done: one per shoal, with how many of its windows are
	 * open.
	 * @param index for shoal_command
	 * @since 4
	 */
	void (*shoal)(void *data,
		      struct abyss_menubar_v1 *abyss_menubar_v1,
		      const char *display,
		      uint32_t island,
		      uint32_t index,
		      const char *name,
		      uint32_t open);
	/**
	 * the window about to be named is confined
	 *
	 * Sent immediately before each focused event (PHASE18 P18.6):
	 * the jail class the focused window's client came in through —
	 * its security context's app id when the engine is AbyssBSD's, the
	 * engine's name otherwise — or empty when it is not confined.
	 * The bar says so in the application's menu.
	 * @since 5
	 */
	void (*jail)(void *data,
		     struct abyss_menubar_v1 *abyss_menubar_v1,
		     const char *class);
	/**
	 * the process a listed window belongs to
	 *
	 * Sent immediately after each window event of a list_islands
	 * answer (PHASE18 P18.13b): the pid of the client that owns the
	 * window, from its socket's credentials, or 0 when it is not
	 * known. The bar matches a window to a process that has said
	 * something of itself (an agent session's presence), to name it in
	 * the island menu and to go to it.
	 * @param id the window just listed
	 * @since 6
	 */
	void (*window_pid)(void *data,
			   struct abyss_menubar_v1 *abyss_menubar_v1,
			   uint32_t id,
			   uint32_t pid);
};

/**
 * @ingroup iface_abyss_menubar_v1
 */
static inline int
abyss_menubar_v1_add_listener(struct abyss_menubar_v1 *abyss_menubar_v1,
			      const struct abyss_menubar_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) abyss_menubar_v1,
				     (void (**)(void)) listener, data);
}

#define ABYSS_MENUBAR_V1_DESTROY 0
#define ABYSS_MENUBAR_V1_FORCE_QUIT 1
#define ABYSS_MENUBAR_V1_LIST_ISLANDS 2
#define ABYSS_MENUBAR_V1_SWITCH_ISLAND 3
#define ABYSS_MENUBAR_V1_SHOAL_COMMAND 4
#define ABYSS_MENUBAR_V1_ACTIVATE_WINDOW 5

/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_FOCUSED_SINCE_VERSION 1
/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_ISLAND_SINCE_VERSION 3
/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_WINDOW_SINCE_VERSION 3
/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_ISLANDS_DONE_SINCE_VERSION 3
/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_SHOAL_SINCE_VERSION 4
/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_JAIL_SINCE_VERSION 5
/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_WINDOW_PID_SINCE_VERSION 6

/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_FORCE_QUIT_SINCE_VERSION 2
/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_LIST_ISLANDS_SINCE_VERSION 3
/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_SWITCH_ISLAND_SINCE_VERSION 3
/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_SHOAL_COMMAND_SINCE_VERSION 4
/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_ACTIVATE_WINDOW_SINCE_VERSION 3

/** @ingroup iface_abyss_menubar_v1 */
static inline void
abyss_menubar_v1_set_user_data(struct abyss_menubar_v1 *abyss_menubar_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) abyss_menubar_v1, user_data);
}

/** @ingroup iface_abyss_menubar_v1 */
static inline void *
abyss_menubar_v1_get_user_data(struct abyss_menubar_v1 *abyss_menubar_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) abyss_menubar_v1);
}

static inline uint32_t
abyss_menubar_v1_get_version(struct abyss_menubar_v1 *abyss_menubar_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) abyss_menubar_v1);
}

/**
 * @ingroup iface_abyss_menubar_v1
 */
static inline void
abyss_menubar_v1_destroy(struct abyss_menubar_v1 *abyss_menubar_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) abyss_menubar_v1,
			 ABYSS_MENUBAR_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) abyss_menubar_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_abyss_menubar_v1
 *
 * Kill every client with a toplevel of this app_id. Only the compositor
 * knows which processes those are, and only the menu bar — on the
 * privileged socket — may ask (PHASE10 P10.8). The compositor never kills
 * itself.
 */
static inline void
abyss_menubar_v1_force_quit(struct abyss_menubar_v1 *abyss_menubar_v1, const char *app_id)
{
	wl_proxy_marshal_flags((struct wl_proxy *) abyss_menubar_v1,
			 ABYSS_MENUBAR_V1_FORCE_QUIT, NULL, wl_proxy_get_version((struct wl_proxy *) abyss_menubar_v1), 0, app_id);
}

/**
 * @ingroup iface_abyss_menubar_v1
 *
 * Answered with a window event for every window that is mapped and not
 * minimised, bottom to top, then islands_done.
 */
static inline void
abyss_menubar_v1_list_islands(struct abyss_menubar_v1 *abyss_menubar_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) abyss_menubar_v1,
			 ABYSS_MENUBAR_V1_LIST_ISLANDS, NULL, wl_proxy_get_version((struct wl_proxy *) abyss_menubar_v1), 0);
}

/**
 * @ingroup iface_abyss_menubar_v1
 */
static inline void
abyss_menubar_v1_switch_island(struct abyss_menubar_v1 *abyss_menubar_v1, const char *display, uint32_t island)
{
	wl_proxy_marshal_flags((struct wl_proxy *) abyss_menubar_v1,
			 ABYSS_MENUBAR_V1_SWITCH_ISLAND, NULL, wl_proxy_get_version((struct wl_proxy *) abyss_menubar_v1), 0, display, island);
}

/**
 * @ingroup iface_abyss_menubar_v1
 *
 * verb is "recall" (arg: a shoal's index), "new" (a shoal of the front
 * window), "add" (the front window to the shoal at arg), "remove" (the
 * front window from its shoal) or "strip" (show or hide the strip).
 */
static inline void
abyss_menubar_v1_shoal_command(struct abyss_menubar_v1 *abyss_menubar_v1, const char *verb, uint32_t arg)
{
	wl_proxy_marshal_flags((struct wl_proxy *) abyss_menubar_v1,
			 ABYSS_MENUBAR_V1_SHOAL_COMMAND, NULL, wl_proxy_get_version((struct wl_proxy *) abyss_menubar_v1), 0, verb, arg);
}

/**
 * @ingroup iface_abyss_menubar_v1
 *
 * Its island, then raised and focused: the Dock's rule.
 */
static inline void
abyss_menubar_v1_activate_window(struct abyss_menubar_v1 *abyss_menubar_v1, uint32_t id)
{
	wl_proxy_marshal_flags((struct wl_proxy *) abyss_menubar_v1,
			 ABYSS_MENUBAR_V1_ACTIVATE_WINDOW, NULL, wl_proxy_get_version((struct wl_proxy *) abyss_menubar_v1), 0, id);
}

#ifdef  __cplusplus
}
#endif

#endif
