/* Generated by wayland-scanner 1.26.0 */

#ifndef ABYSS_MENU_V1_SERVER_PROTOCOL_H
#define ABYSS_MENU_V1_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_abyss_menu_v1 The abyss_menu_v1 protocol
 * whose menus belong to which window
 *
 * @section page_desc_abyss_menu_v1 Description
 *
 * A global menu bar has to show the menus of the application whose window is
 * focused, and only the compositor knows which surface that is. An
 * application therefore tells the compositor, per surface, where its menus
 * are published; the compositor tells the menu bar — and nobody else — where
 * the focused surface's menus are whenever focus moves.
 *
 * The address is bound to a surface, by the client that owns the surface, on
 * the connection that proves it. Nothing here trusts an app_id.
 *
 * @section page_ifaces_abyss_menu_v1 Interfaces
 * - @subpage page_iface_abyss_menu_manager_v1 - publish where a surface's menus live
 * - @subpage page_iface_abyss_menubar_v1 - the menu bar's view of focus
 * @section page_copyright_abyss_menu_v1 Copyright
 * <pre>
 *
 * AbyssBSD Swift DE. PHASE10.md P10.3.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * </pre>
 */
struct abyss_menu_manager_v1;
struct abyss_menubar_v1;
struct wl_surface;

#ifndef ABYSS_MENU_MANAGER_V1_INTERFACE
#define ABYSS_MENU_MANAGER_V1_INTERFACE
/**
 * @page page_iface_abyss_menu_manager_v1 abyss_menu_manager_v1
 * @section page_iface_abyss_menu_manager_v1_desc Description
 *
 * Offered to every client.
 * @section page_iface_abyss_menu_manager_v1_api API
 * See @ref iface_abyss_menu_manager_v1.
 */
/**
 * @defgroup iface_abyss_menu_manager_v1 The abyss_menu_manager_v1 interface
 *
 * Offered to every client.
 */
extern const struct wl_interface abyss_menu_manager_v1_interface;
#endif
#ifndef ABYSS_MENUBAR_V1_INTERFACE
#define ABYSS_MENUBAR_V1_INTERFACE
/**
 * @page page_iface_abyss_menubar_v1 abyss_menubar_v1
 * @section page_iface_abyss_menubar_v1_desc Description
 *
 * Offered only to clients that connected to the compositor's privileged
 * socket (PHASE10 §6.1). It says which application is frontmost and where
 * its menus are, which is exactly what an ordinary client must not learn.
 * @section page_iface_abyss_menubar_v1_api API
 * See @ref iface_abyss_menubar_v1.
 */
/**
 * @defgroup iface_abyss_menubar_v1 The abyss_menubar_v1 interface
 *
 * Offered only to clients that connected to the compositor's privileged
 * socket (PHASE10 §6.1). It says which application is frontmost and where
 * its menus are, which is exactly what an ordinary client must not learn.
 */
extern const struct wl_interface abyss_menubar_v1_interface;
#endif

/**
 * @ingroup iface_abyss_menu_manager_v1
 * @struct abyss_menu_manager_v1_interface
 */
struct abyss_menu_manager_v1_interface {
	/**
	 * destroy the manager; addresses already set remain
	 *
	 * 
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	/**
	 * this surface's menus are published at this address
	 *
	 * Set or replace the menu address of a surface this client owns.
	 * An empty address withdraws it. The address is a CurrentIPC
	 * service name (MenuWire, PHASE10 P10.2). It is forgotten when the
	 * surface is destroyed.
	 */
	void (*set_address)(struct wl_client *client,
			    struct wl_resource *resource,
			    struct wl_resource *surface,
			    const char *address);
};


/**
 * @ingroup iface_abyss_menu_manager_v1
 */
#define ABYSS_MENU_MANAGER_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_abyss_menu_manager_v1
 */
#define ABYSS_MENU_MANAGER_V1_SET_ADDRESS_SINCE_VERSION 1

#ifndef ABYSS_MENUBAR_V1_KIND_ENUM
#define ABYSS_MENUBAR_V1_KIND_ENUM
enum abyss_menubar_v1_kind {
	/**
	 * the focused window publishes no menus, or nothing is focused
	 */
	ABYSS_MENUBAR_V1_KIND_NONE = 0,
	/**
	 * a MenuWire service name
	 */
	ABYSS_MENUBAR_V1_KIND_ABYSS = 1,
	/**
	 * a GTK application's bus name and menu paths (P10.6)
	 */
	ABYSS_MENUBAR_V1_KIND_GTK = 2,
};
#endif /* ABYSS_MENUBAR_V1_KIND_ENUM */

#ifndef ABYSS_MENUBAR_V1_KIND_ENUM_IS_VALID
#define ABYSS_MENUBAR_V1_KIND_ENUM_IS_VALID
/**
 * @ingroup iface_abyss_menubar_v1
 * Validate a abyss_menubar_v1 kind value.
 *
 * @return true on success, false on error.
 * @ref abyss_menubar_v1_kind
 */
static inline bool
abyss_menubar_v1_kind_is_valid(uint32_t value, uint32_t version) {
	switch (value) {
	case ABYSS_MENUBAR_V1_KIND_NONE:
		return version >= 1;
	case ABYSS_MENUBAR_V1_KIND_ABYSS:
		return version >= 1;
	case ABYSS_MENUBAR_V1_KIND_GTK:
		return version >= 1;
	default:
		return false;
	}
}
#endif /* ABYSS_MENUBAR_V1_KIND_ENUM_IS_VALID */

/**
 * @ingroup iface_abyss_menubar_v1
 * @struct abyss_menubar_v1_interface
 */
struct abyss_menubar_v1_interface {
	/**
	 * stop being told
	 *
	 * 
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	/**
	 * end an application that has stopped responding
	 *
	 * Kill every client with a toplevel of this app_id. Only the
	 * compositor knows which processes those are, and only the menu
	 * bar — on the privileged socket — may ask (PHASE10 P10.8).
	 * The compositor never kills itself.
	 * @since 2
	 */
	void (*force_quit)(struct wl_client *client,
			   struct wl_resource *resource,
			   const char *app_id);
};

#define ABYSS_MENUBAR_V1_FOCUSED 0

/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_FOCUSED_SINCE_VERSION 1

/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_abyss_menubar_v1
 */
#define ABYSS_MENUBAR_V1_FORCE_QUIT_SINCE_VERSION 2

/**
 * @ingroup iface_abyss_menubar_v1
 * Sends an focused event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
abyss_menubar_v1_send_focused(struct wl_resource *resource_, uint32_t kind, const char *address, const char *app_id)
{
	wl_resource_post_event(resource_, ABYSS_MENUBAR_V1_FOCUSED, kind, address, app_id);
}

#ifdef  __cplusplus
}
#endif

#endif
