/* Generated by wayland-scanner 1.26.0 */

#ifndef ABYSS_WINDOW_V1_SERVER_PROTOCOL_H
#define ABYSS_WINDOW_V1_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_abyss_window_v1 The abyss_window_v1 protocol
 * window operations xdg-shell does not have
 *
 * @section page_desc_abyss_window_v1 Description
 *
 * xdg-shell lets a client ask to be moved, resized, maximized, minimized
 * and made fullscreen, and never to be sent behind other windows — the
 * depth gadget a window frame may carry (PHASE11.md P11.6). A client that
 * draws its own frame asks undertow here; a frame undertow draws for a
 * client acts directly.
 *
 * The compositor decides. A request is a request: a compositor may ignore
 * it, and a client must not assume its window moved.
 *
 * @section page_ifaces_abyss_window_v1 Interfaces
 * - @subpage page_iface_abyss_window_manager_v1 - window operations
 * @section page_copyright_abyss_window_v1 Copyright
 * <pre>
 *
 * AbyssBSD Swift DE. Same terms as the rest of the tree.
 * </pre>
 */
struct abyss_window_manager_v1;
struct xdg_toplevel;

#ifndef ABYSS_WINDOW_MANAGER_V1_INTERFACE
#define ABYSS_WINDOW_MANAGER_V1_INTERFACE
/**
 * @page page_iface_abyss_window_manager_v1 abyss_window_manager_v1
 * @section page_iface_abyss_window_manager_v1_desc Description
 *
 * A global with no events. Bind it, and ask.
 * @section page_iface_abyss_window_manager_v1_api API
 * See @ref iface_abyss_window_manager_v1.
 */
/**
 * @defgroup iface_abyss_window_manager_v1 The abyss_window_manager_v1 interface
 *
 * A global with no events. Bind it, and ask.
 */
extern const struct wl_interface abyss_window_manager_v1_interface;
#endif

/**
 * @ingroup iface_abyss_window_manager_v1
 * @struct abyss_window_manager_v1_interface
 */
struct abyss_window_manager_v1_interface {
	/**
	 * unbind the manager
	 *
	 * 
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	/**
	 * send a toplevel to the back
	 *
	 * Put the toplevel behind every other window. If it had the
	 * keyboard, the window now in front gets it: a window put away is
	 * not the one being typed into. The toplevel must be one of this
	 * client's.
	 */
	void (*lower)(struct wl_client *client,
		      struct wl_resource *resource,
		      struct wl_resource *toplevel);
};


/**
 * @ingroup iface_abyss_window_manager_v1
 */
#define ABYSS_WINDOW_MANAGER_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_abyss_window_manager_v1
 */
#define ABYSS_WINDOW_MANAGER_V1_LOWER_SINCE_VERSION 1

#ifdef  __cplusplus
}
#endif

#endif
